# Australian Data Residency Enforcement for ACT Placemat Intelligence Hub
# Compliance framework ensuring all data remains within Australia

---
# Australian Data Residency Admission Controller
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionWebhook
metadata:
  name: australian-data-residency-validator
  labels:
    component: compliance
    data-residency: australia
  annotations:
    description: "Validates that all workloads comply with Australian data residency"
    compliance.framework: "australian-privacy-act"
webhooks:
- name: data-residency.validator.actplacemat.org.au
  clientConfig:
    service:
      name: data-residency-validator
      namespace: act-placemat
      path: "/validate-data-residency"
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods", "persistentvolumeclaims"]
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["apps"]
    apiVersions: ["v1"]
    resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["storage.k8s.io"]
    apiVersions: ["v1"]
    resources: ["storageclasses"]
  namespaceSelector:
    matchLabels:
      data-residency: australia
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  failurePolicy: Fail

---
# Australian Storage Classes
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: australian-ssd
  labels:
    data-residency: australia
    compliance-framework: australian-privacy-act
  annotations:
    description: "SSD storage class ensuring Australian data residency"
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  zones: australia-southeast1-a,australia-southeast1-b,australia-southeast1-c
  replication-type: regional-pd
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: australian-standard
  labels:
    data-residency: australia
    compliance-framework: australian-privacy-act
  annotations:
    description: "Standard storage class ensuring Australian data residency"
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  zones: australia-southeast1-a,australia-southeast1-b,australia-southeast1-c
  replication-type: regional-pd
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: australian-backup
  labels:
    data-residency: australia
    compliance-framework: australian-privacy-act
    purpose: backup
  annotations:
    description: "Backup storage class for long-term Australian data retention"
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  zones: australia-southeast2-a,australia-southeast2-b,australia-southeast2-c
  replication-type: regional-pd
allowVolumeExpansion: true
volumeBindingMode: Immediate
reclaimPolicy: Retain

---
# Node Affinity Rules for Australian Data Residency
apiVersion: v1
kind: ConfigMap
metadata:
  name: australian-node-affinity
  namespace: act-placemat
  labels:
    component: compliance
    data-residency: australia
  annotations:
    description: "Node affinity rules for Australian data residency"
    compliance.framework: "australian-privacy-act"
data:
  node_affinity_rules: |
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cloud.google.com/gke-nodepool
            operator: In
            values:
            - australia-southeast1-pool
            - australia-southeast2-pool
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
          - key: data-residency
            operator: In
            values:
            - australia
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: zone
            operator: In
            values:
            - australia-southeast1-a
            - australia-southeast1-b
            - australia-southeast1-c

---
# Pod Security Context for Australian Compliance
apiVersion: v1
kind: ConfigMap
metadata:
  name: australian-security-context
  namespace: act-placemat
  labels:
    component: compliance
    data-residency: australia
  annotations:
    description: "Security context requirements for Australian compliance"
    compliance.framework: "australian-privacy-act"
data:
  security_context: |
    securityContext:
      runAsNonRoot: true
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
      fsGroupChangePolicy: "OnRootMismatch"
      seccompProfile:
        type: RuntimeDefault
      supplementalGroups: [1001]
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1001
      runAsGroup: 1001
      capabilities:
        drop:
        - ALL
        add:
        - NET_BIND_SERVICE  # Only if required
      seccompProfile:
        type: RuntimeDefault

---
# Australian Compliance Network Policy Template
apiVersion: v1
kind: ConfigMap
metadata:
  name: australian-network-policy-template
  namespace: act-placemat
  labels:
    component: compliance
    data-residency: australia
  annotations:
    description: "Network policy template for Australian compliance"
    compliance.framework: "australian-privacy-act"
data:
  network_policy_template: |
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: RESOURCE_NAME-australian-compliance
      namespace: NAMESPACE
      labels:
        data-residency: australia
        compliance-framework: australian-privacy-act
    spec:
      podSelector:
        matchLabels:
          data-residency: australia
      policyTypes:
      - Ingress
      - Egress
      ingress:
      - from:
        - namespaceSelector:
            matchLabels:
              data-residency: australia
        - podSelector:
            matchLabels:
              data-residency: australia
      egress:
      - to:
        - namespaceSelector:
            matchLabels:
              data-residency: australia
        - podSelector:
            matchLabels:
              data-residency: australia
      - to: []
        ports:
        - protocol: TCP
          port: 443  # HTTPS only for external
        - protocol: TCP
          port: 53   # DNS
        - protocol: UDP
          port: 53   # DNS

---
# Australian Data Classification ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: australian-data-classification
  namespace: act-placemat
  labels:
    component: compliance
    data-residency: australia
  annotations:
    description: "Data classification scheme for Australian compliance"
    compliance.framework: "australian-privacy-act"
data:
  classification_levels: |
    - level: public
      description: "Information that can be freely shared with the public"
      retention: "indefinite"
      encryption: "optional"
      audit: "basic"
      
    - level: community
      description: "Information shared within the ACT Placemat community"
      retention: "7-years"
      encryption: "recommended"
      audit: "standard"
      
    - level: internal
      description: "Internal organizational information"
      retention: "7-years"
      encryption: "required"
      audit: "detailed"
      
    - level: confidential
      description: "Sensitive information requiring protection"
      retention: "7-years"
      encryption: "required"
      audit: "comprehensive"
      
    - level: restricted
      description: "Highly sensitive information with strict access controls"
      retention: "7-years"
      encryption: "required"
      audit: "comprehensive"
      access_control: "role-based"

  handling_requirements: |
    public:
      storage_location: "australia-preferred"
      backup_required: false
      encryption_at_rest: false
      encryption_in_transit: true
      audit_logging: "basic"
      
    community:
      storage_location: "australia-required"
      backup_required: true
      encryption_at_rest: true
      encryption_in_transit: true
      audit_logging: "standard"
      
    internal:
      storage_location: "australia-required"
      backup_required: true
      encryption_at_rest: true
      encryption_in_transit: true
      audit_logging: "detailed"
      
    confidential:
      storage_location: "australia-required"
      backup_required: true
      encryption_at_rest: true
      encryption_in_transit: true
      audit_logging: "comprehensive"
      access_review_required: true
      
    restricted:
      storage_location: "australia-required"
      backup_required: true
      encryption_at_rest: true
      encryption_in_transit: true
      audit_logging: "comprehensive"
      access_review_required: true
      approval_required: true

---
# Australian Privacy Impact Assessment ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: australian-privacy-impact-assessment
  namespace: act-placemat
  labels:
    component: compliance
    data-residency: australia
  annotations:
    description: "Privacy Impact Assessment for Australian compliance"
    compliance.framework: "australian-privacy-act"
data:
  pia_summary: |
    Privacy Impact Assessment for ACT Placemat Intelligence Hub
    
    Assessment Date: 2024-08-15
    Compliance Framework: Australian Privacy Act 1988
    Data Residency: Australia
    
    Data Types Processed:
    - Community interaction data
    - Task processing metadata
    - System logs and metrics
    - Agent communication data
    - User preferences and settings
    
    Privacy Controls Implemented:
    - Data minimization
    - Purpose limitation
    - Storage limitation (7-year retention)
    - Data security (encryption at rest and in transit)
    - Access controls (RBAC)
    - Audit logging
    - Data subject rights (access, correction, deletion)
    
    Risk Mitigation:
    - All data stored within Australia
    - Regular security assessments
    - Staff training on privacy requirements
    - Incident response procedures
    - Data breach notification procedures
    
    Conclusion: The ACT Placemat Intelligence Hub has been assessed
    as compliant with the Australian Privacy Act 1988 with appropriate
    technical and organizational measures in place.

  privacy_principles: |
    Australian Privacy Principles (APPs) Compliance:
    
    APP 1 - Open and transparent management:
      Status: Compliant
      Evidence: Privacy policy published, clear data handling practices
      
    APP 2 - Anonymity and pseudonymity:
      Status: Compliant
      Evidence: Optional anonymized community participation
      
    APP 3 - Collection of solicited personal information:
      Status: Compliant
      Evidence: Collection limited to necessary purposes
      
    APP 4 - Dealing with unsolicited personal information:
      Status: Compliant
      Evidence: Procedures for handling unsolicited information
      
    APP 5 - Notification of collection:
      Status: Compliant
      Evidence: Users notified of collection purposes
      
    APP 6 - Use or disclosure:
      Status: Compliant
      Evidence: Use limited to stated purposes
      
    APP 7 - Direct marketing:
      Status: Not Applicable
      Evidence: No direct marketing activities
      
    APP 8 - Cross-border disclosure:
      Status: Compliant
      Evidence: No cross-border transfers, Australia-only storage
      
    APP 9 - Government related identifiers:
      Status: Compliant
      Evidence: No government identifiers collected
      
    APP 10 - Quality of personal information:
      Status: Compliant
      Evidence: Data accuracy procedures in place
      
    APP 11 - Security:
      Status: Compliant
      Evidence: Encryption, access controls, audit logging
      
    APP 12 - Access to personal information:
      Status: Compliant
      Evidence: Individual access rights implemented
      
    APP 13 - Correction:
      Status: Compliant
      Evidence: Data correction procedures available

---
# Australian Compliance Monitoring CronJob
apiVersion: batch/v1
kind: CronJob
metadata:
  name: australian-compliance-audit
  namespace: act-placemat
  labels:
    component: compliance
    data-residency: australia
  annotations:
    description: "Automated Australian compliance auditing"
    compliance.framework: "australian-privacy-act"
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM AEDT
  timeZone: "Australia/Sydney"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            component: compliance-audit
            data-residency: australia
        spec:
          serviceAccountName: compliance-auditor
          restartPolicy: OnFailure
          containers:
          - name: compliance-audit
            image: registry.actplacemat.org.au:5000/act-placemat/compliance-auditor:latest
            imagePullPolicy: Always
            env:
            - name: TZ
              value: "Australia/Sydney"
            - name: DATA_RESIDENCY
              value: "australia"
            - name: COMPLIANCE_FRAMEWORK
              value: "australian-privacy-act"
            - name: AUDIT_SCOPE
              value: "full"
            command:
            - /bin/sh
            - -c
            - |
              echo "Starting Australian compliance audit at $(date)"
              
              # Check data residency compliance
              kubectl get pods -A -o json | jq -r '.items[] | select(.metadata.labels."data-residency" != "australia") | .metadata.name' > /tmp/non-compliant-pods.txt
              
              # Check storage compliance
              kubectl get pv -o json | jq -r '.items[] | select(.spec.nodeAffinity.required.nodeSelectorTerms[0].matchExpressions[] | select(.key == "kubernetes.io/zone" and (.values[] | test("australia") | not))) | .metadata.name' > /tmp/non-compliant-storage.txt
              
              # Generate compliance report
              cat > /tmp/compliance-report.json << EOF
              {
                "audit_date": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
                "timezone": "Australia/Sydney",
                "compliance_framework": "Australian Privacy Act 1988",
                "data_residency": "australia",
                "audit_scope": "full",
                "findings": {
                  "non_compliant_pods": $(cat /tmp/non-compliant-pods.txt | wc -l),
                  "non_compliant_storage": $(cat /tmp/non-compliant-storage.txt | wc -l)
                },
                "status": "$([ $(cat /tmp/non-compliant-pods.txt | wc -l) -eq 0 ] && [ $(cat /tmp/non-compliant-storage.txt | wc -l) -eq 0 ] && echo "COMPLIANT" || echo "NON_COMPLIANT")"
              }
              EOF
              
              # Store audit results
              kubectl create configmap compliance-audit-$(date +%Y%m%d) --from-file=/tmp/compliance-report.json -n act-placemat --dry-run=client -o yaml | kubectl apply -f -
              
              echo "Australian compliance audit completed at $(date)"
            resources:
              limits:
                cpu: 100m
                memory: 256Mi
              requests:
                cpu: 50m
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 1001
              capabilities:
                drop:
                - ALL
            volumeMounts:
            - name: tmp
              mountPath: /tmp
          volumes:
          - name: tmp
            emptyDir: {}
          imagePullSecrets:
          - name: registry-credentials
          nodeSelector:
            data-residency: australia