# Service Account Key Management for ACT Placemat Intelligence Hub
# Australian-compliant key rotation, encryption, and lifecycle management

---
# Key Management ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: key-management-config
  namespace: act-placemat
  labels:
    component: key-management
    data-residency: australia
  annotations:
    description: "Configuration for service account key management"
    compliance.framework: "australian-privacy-act"
data:
  # Key rotation policies
  key_rotation_interval: "90d"  # 90 days
  emergency_rotation_interval: "24h"
  key_expiry_warning: "7d"
  
  # Key storage configuration
  key_storage_location: "australia"
  encryption_algorithm: "AES-256-GCM"
  key_derivation_function: "PBKDF2"
  key_derivation_iterations: "100000"
  
  # Audit configuration
  key_access_logging: "enabled"
  key_rotation_logging: "enabled"
  failed_access_alerting: "enabled"
  
  # Australian compliance
  data_residency: "australia"
  compliance_framework: "australian-privacy-act"
  retention_period: "7-years"
  key_escrow_required: "false"
  
  # Supported key types
  supported_key_types: |
    - rsa-2048
    - rsa-4096
    - ecdsa-p256
    - ecdsa-p384
    - ed25519
  
  # Key usage policies
  key_usage_policies: |
    authentication:
      max_age: "90d"
      min_strength: "rsa-2048"
      rotation_required: true
      
    encryption:
      max_age: "365d"
      min_strength: "rsa-4096"
      rotation_required: true
      
    signing:
      max_age: "180d"
      min_strength: "ecdsa-p256"
      rotation_required: true

---
# Key Management Secrets (encrypted keys)
apiVersion: v1
kind: Secret
metadata:
  name: key-management-secrets
  namespace: act-placemat
  labels:
    component: key-management
    data-residency: australia
  annotations:
    description: "Encrypted keys for key management operations"
    compliance.framework: "australian-privacy-act"
    data.classification: "restricted"
    audit.required: "true"
type: Opaque
data:
  # Master encryption keys (base64 encoded, encrypted)
  master_encryption_key: ${MASTER_ENCRYPTION_KEY_B64}
  key_derivation_salt: ${KEY_DERIVATION_SALT_B64}
  
  # Key Management Service keys
  kms_encryption_key: ${KMS_ENCRYPTION_KEY_B64}
  kms_signing_key: ${KMS_SIGNING_KEY_B64}
  
  # Certificate Authority keys
  ca_private_key: ${CA_PRIVATE_KEY_B64}
  ca_certificate: ${CA_CERTIFICATE_B64}
  
  # Audit signing keys
  audit_signing_key: ${AUDIT_SIGNING_KEY_B64}
  audit_verification_key: ${AUDIT_VERIFICATION_KEY_B64}

---
# Key Management Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: key-management-service
  namespace: act-placemat
  labels:
    component: key-management
    data-residency: australia
  annotations:
    description: "Service account for key management operations"
    compliance.framework: "australian-privacy-act"
    data.classification: "restricted"
    audit.required: "true"
automountServiceAccountToken: true

---
# Key Management RBAC Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: key-management
  namespace: act-placemat
  labels:
    component: key-management
    data-residency: australia
  annotations:
    description: "Role for key management operations"
    compliance.framework: "australian-privacy-act"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  resourceNames: 
    - "key-management-secrets"
    - "registry-credentials"
    - "harbor-credentials"
    - "langgraph-secrets"
    - "api-keys"
    - "agent-config"
    - "financial-api-keys"
    - "research-api-keys"
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
  resourceNames:
    - "key-management-config"
    - "key-rotation-log"
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]

---
# Key Management Role Binding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: key-management-binding
  namespace: act-placemat
  labels:
    component: key-management
    data-residency: australia
  annotations:
    description: "Binds key-management-service to key management role"
    compliance.framework: "australian-privacy-act"
subjects:
- kind: ServiceAccount
  name: key-management-service
  namespace: act-placemat
roleRef:
  kind: Role
  name: key-management
  apiGroup: rbac.authorization.k8s.io

---
# Key Rotation CronJob
apiVersion: batch/v1
kind: CronJob
metadata:
  name: key-rotation
  namespace: act-placemat
  labels:
    component: key-management
    data-residency: australia
  annotations:
    description: "Automated key rotation for Australian compliance"
    compliance.framework: "australian-privacy-act"
spec:
  schedule: "0 3 */90 * *"  # Every 90 days at 3 AM AEDT
  timeZone: "Australia/Sydney"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            component: key-rotation
            data-residency: australia
        spec:
          serviceAccountName: key-management-service
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            fsGroup: 1001
          containers:
          - name: key-rotator
            image: registry.actplacemat.org.au:5000/act-placemat/key-rotator:latest
            imagePullPolicy: Always
            env:
            - name: TZ
              value: "Australia/Sydney"
            - name: DATA_RESIDENCY
              value: "australia"
            - name: COMPLIANCE_FRAMEWORK
              value: "australian-privacy-act"
            - name: ROTATION_TYPE
              value: "scheduled"
            - name: NAMESPACE
              value: "act-placemat"
            command:
            - /bin/sh
            - -c
            - |
              echo "Starting key rotation at $(date)"
              
              # Check key ages
              CURRENT_DATE=$(date +%s)
              ROTATION_THRESHOLD=7776000  # 90 days in seconds
              
              # Function to check and rotate keys
              rotate_key_if_needed() {
                local secret_name=$1
                local key_name=$2
                
                echo "Checking key age for $secret_name/$key_name"
                
                # Get secret creation time
                CREATION_TIME=$(kubectl get secret $secret_name -o jsonpath='{.metadata.creationTimestamp}' -n act-placemat)
                CREATION_TIMESTAMP=$(date -d "$CREATION_TIME" +%s)
                AGE=$((CURRENT_DATE - CREATION_TIMESTAMP))
                
                if [ $AGE -gt $ROTATION_THRESHOLD ]; then
                  echo "Key $secret_name/$key_name is $AGE seconds old, rotating..."
                  
                  # Generate new key (placeholder - implement actual key generation)
                  NEW_KEY=$(openssl rand -base64 32)
                  
                  # Update secret with new key
                  kubectl patch secret $secret_name -p "{\"data\":{\"$key_name\":\"$(echo -n $NEW_KEY | base64 -w 0)\"}}" -n act-placemat
                  
                  # Log rotation
                  kubectl create event key-rotated-$secret_name-$(date +%s) \
                    --message="Key $key_name in secret $secret_name rotated due to age ($AGE seconds)" \
                    --reason="KeyRotation" \
                    --type="Normal" \
                    --source="key-rotation-cronjob" \
                    --namespace=act-placemat
                  
                  echo "Key $secret_name/$key_name rotated successfully"
                else
                  echo "Key $secret_name/$key_name is $AGE seconds old, no rotation needed"
                fi
              }
              
              # Rotate service account keys
              rotate_key_if_needed "langgraph-secrets" "state_encryption_key"
              rotate_key_if_needed "langgraph-secrets" "checkpoint_encryption_key"
              rotate_key_if_needed "key-management-secrets" "audit_signing_key"
              
              # Log completion
              kubectl create configmap key-rotation-log-$(date +%Y%m%d) \
                --from-literal="rotation_date=$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
                --from-literal="rotation_type=scheduled" \
                --from-literal="compliance_framework=australian-privacy-act" \
                --from-literal="data_residency=australia" \
                -n act-placemat --dry-run=client -o yaml | kubectl apply -f -
              
              echo "Key rotation completed at $(date)"
            resources:
              limits:
                cpu: 200m
                memory: 512Mi
              requests:
                cpu: 100m
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 1001
              capabilities:
                drop:
                - ALL
            volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: key-config
              mountPath: /app/config
              readOnly: true
          volumes:
          - name: tmp
            emptyDir: {}
          - name: key-config
            configMap:
              name: key-management-config
          imagePullSecrets:
          - name: registry-credentials
          nodeSelector:
            data-residency: australia

---
# Emergency Key Rotation Job Template
apiVersion: batch/v1
kind: Job
metadata:
  name: emergency-key-rotation-template
  namespace: act-placemat
  labels:
    component: key-management
    rotation-type: emergency
    data-residency: australia
  annotations:
    description: "Template for emergency key rotation"
    compliance.framework: "australian-privacy-act"
    usage: "This is a template. Create actual jobs with unique names."
spec:
  template:
    metadata:
      labels:
        component: emergency-key-rotation
        data-residency: australia
    spec:
      serviceAccountName: key-management-service
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: emergency-key-rotator
        image: registry.actplacemat.org.au:5000/act-placemat/key-rotator:latest
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "Australia/Sydney"
        - name: DATA_RESIDENCY
          value: "australia"
        - name: COMPLIANCE_FRAMEWORK
          value: "australian-privacy-act"
        - name: ROTATION_TYPE
          value: "emergency"
        - name: NAMESPACE
          value: "act-placemat"
        - name: TARGET_SECRET
          value: "REPLACE_WITH_SECRET_NAME"
        - name: TARGET_KEY
          value: "REPLACE_WITH_KEY_NAME"
        command:
        - /bin/sh
        - -c
        - |
          echo "Starting emergency key rotation at $(date)"
          echo "Target: $TARGET_SECRET/$TARGET_KEY"
          
          # Generate new key immediately
          NEW_KEY=$(openssl rand -base64 32)
          
          # Backup old key
          OLD_KEY=$(kubectl get secret $TARGET_SECRET -o jsonpath="{.data.$TARGET_KEY}" -n act-placemat)
          kubectl create secret generic $TARGET_SECRET-backup-$(date +%s) \
            --from-literal="$TARGET_KEY=$OLD_KEY" \
            --from-literal="backup_date=$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
            --from-literal="reason=emergency-rotation" \
            -n act-placemat
          
          # Update secret with new key
          kubectl patch secret $TARGET_SECRET -p "{\"data\":{\"$TARGET_KEY\":\"$(echo -n $NEW_KEY | base64 -w 0)\"}}" -n act-placemat
          
          # Log emergency rotation
          kubectl create event emergency-key-rotated-$TARGET_SECRET-$(date +%s) \
            --message="Emergency rotation of key $TARGET_KEY in secret $TARGET_SECRET" \
            --reason="EmergencyKeyRotation" \
            --type="Warning" \
            --source="emergency-key-rotation-job" \
            --namespace=act-placemat
          
          echo "Emergency key rotation completed at $(date)"
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      imagePullSecrets:
      - name: registry-credentials
      nodeSelector:
        data-residency: australia

---
# Key Monitoring ServiceMonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: key-management-metrics
  namespace: act-placemat
  labels:
    component: key-management
    data-residency: australia
  annotations:
    description: "Monitoring for key management operations"
    compliance.framework: "australian-privacy-act"
spec:
  selector:
    matchLabels:
      component: key-management
  endpoints:
  - port: metrics
    interval: 60s
    path: /metrics
    honorLabels: true
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_label_data_residency]
      targetLabel: data_residency
    - sourceLabels: [__meta_kubernetes_pod_annotation_compliance_framework]
      targetLabel: compliance_framework

---
# Key Age Alert Rule
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: key-management-alerts
  namespace: act-placemat
  labels:
    component: key-management
    data-residency: australia
  annotations:
    description: "Alert rules for key management"
    compliance.framework: "australian-privacy-act"
spec:
  groups:
  - name: key-management
    rules:
    - alert: KeyRotationOverdue
      expr: (time() - kube_secret_created) / 86400 > 90
      for: 1h
      labels:
        severity: warning
        component: key-management
        data_residency: australia
      annotations:
        summary: "Service account key rotation overdue"
        description: "Key {{ $labels.secret }} is {{ $value }} days old and should be rotated"
        
    - alert: KeyRotationFailed
      expr: increase(job_failures_total{job_name=~"key-rotation.*"}[1h]) > 0
      for: 0m
      labels:
        severity: critical
        component: key-management
        data_residency: australia
      annotations:
        summary: "Key rotation job failed"
        description: "Key rotation job {{ $labels.job_name }} has failed"
        
    - alert: UnauthorizedKeyAccess
      expr: increase(key_access_denied_total[5m]) > 0
      for: 0m
      labels:
        severity: critical
        component: security
        data_residency: australia
      annotations:
        summary: "Unauthorized key access detected"
        description: "{{ $value }} unauthorized key access attempts in the last 5 minutes"