# RBAC Roles for ACT Placemat Intelligence Hub
# Australian-compliant role-based access control with least privilege

---
# Intelligence Hub Orchestrator Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: intelligence-hub-orchestrator
  namespace: act-placemat
  labels:
    component: orchestrator
    data-residency: australia
  annotations:
    description: "Role for Intelligence Hub orchestrator with task management permissions"
    compliance.framework: "australian-privacy-act"
    data.classification: "internal"
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]

---
# Agent Base Role (inherited by all agents)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agent-base
  namespace: act-placemat
  labels:
    component: agent
    data-residency: australia
  annotations:
    description: "Base role for all Intelligence Hub agents"
    compliance.framework: "australian-privacy-act"
    data.classification: "internal"
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["api-keys", "agent-config"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
  resourceNames: ["self"]

---
# Financial Intelligence Agent Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: financial-intelligence-agent
  namespace: act-placemat
  labels:
    component: agent
    agent-type: financial-intelligence
    data-residency: australia
  annotations:
    description: "Role for Financial Intelligence Agent with financial data access"
    compliance.framework: "australian-privacy-act"
    data.classification: "confidential"
    capabilities: "financial-analysis,market-research,risk-assessment,abn-lookup"
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["financial-api-keys", "abn-lookup-credentials", "asic-api-keys"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list"]

---
# Research Analyst Agent Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: research-analyst-agent
  namespace: act-placemat
  labels:
    component: agent
    agent-type: research-analyst
    data-residency: australia
  annotations:
    description: "Role for Research Analyst Agent with research capabilities"
    compliance.framework: "australian-privacy-act"
    data.classification: "internal"
    capabilities: "web-scraping,data-analysis,report-generation,fact-checking"
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["research-api-keys", "web-scraping-config"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list"]

---
# Compliance Officer Agent Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: compliance-officer-agent
  namespace: act-placemat
  labels:
    component: agent
    agent-type: compliance-officer
    data-residency: australia
  annotations:
    description: "Role for Compliance Officer Agent with audit and compliance permissions"
    compliance.framework: "australian-privacy-act"
    data.classification: "confidential"
    capabilities: "privacy-audit,regulatory-check,data-classification,australian-law-check"
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "create"]
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch"]

---
# Community Coordinator Agent Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: community-coordinator-agent
  namespace: act-placemat
  labels:
    component: agent
    agent-type: community-coordinator
    data-residency: australia
  annotations:
    description: "Role for Community Coordinator Agent with community engagement permissions"
    compliance.framework: "australian-privacy-act"
    data.classification: "community"
    capabilities: "stakeholder-engagement,democratic-processes,consensus-building"
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
  resourceNames: ["community-config", "democratic-voting", "consensus-state"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["community-api-keys"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---
# Registry Access Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: registry-access
  namespace: act-placemat
  labels:
    component: registry
    data-residency: australia
  annotations:
    description: "Role for Docker registry access and image management"
    compliance.framework: "australian-privacy-act"
    data.classification: "operational"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
  resourceNames: ["registry-credentials", "harbor-credentials"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
  resourceNames: ["registry-config"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---
# Monitoring Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitoring
  namespace: act-placemat
  labels:
    component: monitoring
    data-residency: australia
  annotations:
    description: "Role for monitoring and observability systems"
    compliance.framework: "australian-privacy-act"
    data.classification: "operational"
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]

---
# Backup and Recovery Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backup-recovery
  namespace: act-placemat
  labels:
    component: backup
    data-residency: australia
  annotations:
    description: "Role for backup and recovery operations"
    compliance.framework: "australian-privacy-act"
    data.classification: "confidential"
rules:
- apiGroups: [""]
  resources: ["persistentvolumes", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create"]
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create"]

---
# Australian Compliance Auditor Role (Read-only)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: compliance-auditor
  namespace: act-placemat
  labels:
    component: compliance
    data-residency: australia
  annotations:
    description: "Read-only role for Australian compliance auditing"
    compliance.framework: "australian-privacy-act"
    data.classification: "confidential"
    compliance.role: "auditor"
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["policy"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]

---
# Cluster Role for Node Access (Monitoring)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: act-placemat-node-reader
  labels:
    component: monitoring
    data-residency: australia
  annotations:
    description: "Cluster role for reading node metrics and status"
    compliance.framework: "australian-privacy-act"
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/proxy", "nodes/metrics"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]

---
# Australian Data Residency Cluster Role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: australian-data-residency-enforcer
  labels:
    component: compliance
    data-residency: australia
  annotations:
    description: "Cluster role for enforcing Australian data residency"
    compliance.framework: "australian-privacy-act"
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  verbs: ["get", "list", "watch", "create", "update"]