# Service Accounts Configuration for ACT Placemat Intelligence Hub
# Australian-compliant RBAC with least-privilege access

apiVersion: v1
kind: Namespace
metadata:
  name: act-placemat
  labels:
    data-residency: australia
    compliance-framework: australian-privacy-act
    environment: production

---
# Core Intelligence Hub Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: intelligence-hub
  namespace: act-placemat
  labels:
    app: intelligence-hub
    component: orchestrator
    data-residency: australia
  annotations:
    description: "Core service account for Intelligence Hub orchestrator"
    compliance.framework: "australian-privacy-act"
    data.classification: "internal"
    audit.required: "true"
automountServiceAccountToken: true

---
# Financial Intelligence Agent Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: financial-intelligence-agent
  namespace: act-placemat
  labels:
    app: intelligence-hub
    component: agent
    agent-type: financial-intelligence
    data-residency: australia
  annotations:
    description: "Service account for Financial Intelligence Agent"
    agent.capabilities: "financial-analysis,market-research,risk-assessment,abn-lookup"
    data.classification: "confidential"
    audit.required: "true"
automountServiceAccountToken: true

---
# Research Analyst Agent Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: research-analyst-agent
  namespace: act-placemat
  labels:
    app: intelligence-hub
    component: agent
    agent-type: research-analyst
    data-residency: australia
  annotations:
    description: "Service account for Research Analyst Agent"
    agent.capabilities: "web-scraping,data-analysis,report-generation,fact-checking"
    data.classification: "internal"
    audit.required: "true"
automountServiceAccountToken: true

---
# Compliance Officer Agent Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: compliance-officer-agent
  namespace: act-placemat
  labels:
    app: intelligence-hub
    component: agent
    agent-type: compliance-officer
    data-residency: australia
  annotations:
    description: "Service account for Compliance Officer Agent"
    agent.capabilities: "privacy-audit,regulatory-check,data-classification,australian-law-check"
    data.classification: "confidential"
    audit.required: "true"
automountServiceAccountToken: true

---
# Community Coordinator Agent Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: community-coordinator-agent
  namespace: act-placemat
  labels:
    app: intelligence-hub
    component: agent
    agent-type: community-coordinator
    data-residency: australia
  annotations:
    description: "Service account for Community Coordinator Agent"
    agent.capabilities: "stakeholder-engagement,democratic-processes,consensus-building"
    data.classification: "community"
    audit.required: "true"
automountServiceAccountToken: true

---
# Registry Access Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry-access
  namespace: act-placemat
  labels:
    app: intelligence-hub
    component: registry
    data-residency: australia
  annotations:
    description: "Service account for Docker registry access"
    access.type: "registry-pull-push"
    data.classification: "operational"
    audit.required: "true"
automountServiceAccountToken: true

---
# Monitoring Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring
  namespace: act-placemat
  labels:
    app: intelligence-hub
    component: monitoring
    data-residency: australia
  annotations:
    description: "Service account for monitoring and observability"
    access.type: "metrics-collection"
    data.classification: "operational"
    audit.required: "true"
automountServiceAccountToken: true

---
# Backup and Recovery Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-recovery
  namespace: act-placemat
  labels:
    app: intelligence-hub
    component: backup
    data-residency: australia
  annotations:
    description: "Service account for backup and recovery operations"
    access.type: "backup-restore"
    data.classification: "confidential"
    audit.required: "true"
automountServiceAccountToken: true

---
# Australian Compliance Auditor Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: compliance-auditor
  namespace: act-placemat
  labels:
    app: intelligence-hub
    component: compliance
    data-residency: australia
  annotations:
    description: "Service account for Australian compliance auditing"
    access.type: "audit-read-only"
    data.classification: "confidential"
    audit.required: "true"
    compliance.role: "auditor"
automountServiceAccountToken: true

---
# Network Policy for Australian Compliance
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: act-placemat-network-policy
  namespace: act-placemat
  labels:
    data-residency: australia
    compliance-framework: australian-privacy-act
spec:
  podSelector:
    matchLabels:
      data-residency: australia
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: act-placemat
    - podSelector:
        matchLabels:
          data-residency: australia
    ports:
    - protocol: TCP
      port: 3002
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 9090
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: act-placemat
    - podSelector:
        matchLabels:
          data-residency: australia
    ports:
    - protocol: TCP
      port: 5432
    - protocol: TCP
      port: 6379
    - protocol: TCP
      port: 5000
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80

---
# Australian Data Residency ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: australian-compliance-config
  namespace: act-placemat
  labels:
    data-residency: australia
    compliance-framework: australian-privacy-act
data:
  DATA_RESIDENCY: "Australia"
  COMPLIANCE_FRAMEWORK: "Australian-Privacy-Act"
  TIMEZONE: "Australia/Sydney"
  LOCALE: "en-AU"
  CURRENCY: "AUD"
  RETENTION_PERIOD: "7-years"
  AUDIT_REQUIRED: "true"
  ENCRYPTION_REQUIRED: "true"
  PRIVACY_IMPACT_ASSESSMENT: "completed"
  DATA_CLASSIFICATION_LEVELS: "public,community,internal,confidential,restricted"
  AUSTRALIAN_REGIONS: "australia-southeast1,australia-southeast2"
  COMPLIANCE_CONTACT: "compliance@actplacemat.org.au"
  PRIVACY_OFFICER: "privacy@actplacemat.org.au"
  DPO_CONTACT: "dpo@actplacemat.org.au"