# Workload Identity Federation Configuration for ACT Placemat Intelligence Hub
# Secure CI/CD authentication for GitHub Actions without long-lived credentials

---
# Workload Identity Pool Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: workload-identity-federation-config
  namespace: act-placemat
  labels:
    component: workload-identity
    data-residency: australia
  annotations:
    description: "Workload Identity Federation configuration for GitHub Actions"
    compliance.framework: "australian-privacy-act"
data:
  wif_config: |
    # Google Cloud project configuration
    project_id: "act-placemat-intelligence-hub"
    project_number: "123456789012"  # Replace with actual project number
    region: "australia-southeast1"
    
    # Workload Identity Pool
    identity_pool:
      pool_id: "github-actions-pool"
      pool_display_name: "GitHub Actions Pool"
      pool_description: "Identity pool for GitHub Actions CI/CD workflows"
      location: "global"
      
    # GitHub OIDC Provider
    oidc_provider:
      provider_id: "github-actions-provider"
      provider_display_name: "GitHub Actions OIDC Provider"
      issuer_uri: "https://token.actions.githubusercontent.com"
      allowed_audiences: ["sts.googleapis.com"]
      
    # Attribute mappings
    attribute_mapping:
      "google.subject": "assertion.sub"
      "attribute.actor": "assertion.actor"
      "attribute.repository": "assertion.repository"
      "attribute.repository_owner": "assertion.repository_owner"
      "attribute.ref": "assertion.ref"
      "attribute.ref_type": "assertion.ref_type"
      "attribute.workflow": "assertion.workflow"
      "attribute.job_workflow_ref": "assertion.job_workflow_ref"
      "attribute.event_name": "assertion.event_name"
      
    # Attribute conditions for security
    attribute_condition: |
      assertion.repository_owner == "benknight" &&
      assertion.repository == "benknight/ACT-Placemat" &&
      (
        assertion.ref == "refs/heads/main" ||
        assertion.ref == "refs/heads/unified-intelligence" ||
        assertion.ref.startsWith("refs/heads/feature/") ||
        assertion.ref.startsWith("refs/heads/hotfix/") ||
        assertion.ref.startsWith("refs/tags/v")
      )

  # Service account mappings
  service_account_mappings: |
    # CI/CD Service Accounts
    ci_cd_deployment:
      service_account: "github-actions-deploy@act-placemat-intelligence-hub.iam.gserviceaccount.com"
      workload_identity_user: "principalSet://iam.googleapis.com/projects/123456789012/locations/global/workloadIdentityPools/github-actions-pool/attribute.repository/benknight/ACT-Placemat"
      roles:
        - "roles/container.developer"
        - "roles/secretmanager.secretAccessor"
        - "roles/storage.objectAdmin"
        - "roles/cloudsql.client"
        
    ci_cd_testing:
      service_account: "github-actions-test@act-placemat-intelligence-hub.iam.gserviceaccount.com"
      workload_identity_user: "principalSet://iam.googleapis.com/projects/123456789012/locations/global/workloadIdentityPools/github-actions-pool/attribute.repository/benknight/ACT-Placemat"
      roles:
        - "roles/container.developer"
        - "roles/secretmanager.secretAccessor"
        - "roles/storage.objectViewer"
        
    ci_cd_security_scan:
      service_account: "github-actions-security@act-placemat-intelligence-hub.iam.gserviceaccount.com"
      workload_identity_user: "principalSet://iam.googleapis.com/projects/123456789012/locations/global/workloadIdentityPools/github-actions-pool/attribute.repository/benknight/ACT-Placemat"
      roles:
        - "roles/container.developer"
        - "roles/binaryauthorization.attestorsVerifier"
        - "roles/cloudsecurity.findingsEditor"

  # Australian compliance requirements
  compliance_requirements: |
    # Data residency
    data_location: "australia"
    audit_logging: "comprehensive"
    
    # Security requirements
    token_lifetime: "3600s"  # 1 hour
    require_mfa: false  # Not applicable for workload identity
    allowed_ip_ranges: []  # GitHub Actions IPs vary
    
    # Monitoring
    failed_auth_alerts: true
    unusual_activity_detection: true
    compliance_reporting: "weekly"

---
# GitHub Actions Service Account for Deployment
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions-deploy
  namespace: act-placemat
  labels:
    component: workload-identity
    role: deployment
    data-residency: australia
  annotations:
    description: "Service account for GitHub Actions deployment workflows"
    compliance.framework: "australian-privacy-act"
    iam.gke.io/gcp-service-account: "github-actions-deploy@act-placemat-intelligence-hub.iam.gserviceaccount.com"
    data.classification: "internal"
    audit.required: "true"
automountServiceAccountToken: true

---
# GitHub Actions Service Account for Testing
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions-test
  namespace: act-placemat
  labels:
    component: workload-identity
    role: testing
    data-residency: australia
  annotations:
    description: "Service account for GitHub Actions testing workflows"
    compliance.framework: "australian-privacy-act"
    iam.gke.io/gcp-service-account: "github-actions-test@act-placemat-intelligence-hub.iam.gserviceaccount.com"
    data.classification: "internal"
    audit.required: "true"
automountServiceAccountToken: true

---
# GitHub Actions Service Account for Security Scanning
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions-security
  namespace: act-placemat
  labels:
    component: workload-identity
    role: security-scan
    data-residency: australia
  annotations:
    description: "Service account for GitHub Actions security scanning workflows"
    compliance.framework: "australian-privacy-act"
    iam.gke.io/gcp-service-account: "github-actions-security@act-placemat-intelligence-hub.iam.gserviceaccount.com"
    data.classification: "internal"
    audit.required: "true"
automountServiceAccountToken: true

---
# RBAC Role for GitHub Actions Deployment
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-actions-deploy
  namespace: act-placemat
  labels:
    component: workload-identity
    data-residency: australia
  annotations:
    description: "Role for GitHub Actions deployment operations"
    compliance.framework: "australian-privacy-act"
rules:
# Deployment management
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
# Secret access for deployment
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
  resourceNames: ["agent-api-keys", "database-credentials", "registry-credentials"]
# Service account token creation
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs: ["create"]
  resourceNames: ["github-actions-deploy"]
# Event logging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]

---
# RBAC Role for GitHub Actions Testing
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-actions-test
  namespace: act-placemat
  labels:
    component: workload-identity
    data-residency: australia
  annotations:
    description: "Role for GitHub Actions testing operations"
    compliance.framework: "australian-privacy-act"
rules:
# Read-only access for testing
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
# Limited secret access for testing
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
  resourceNames: ["agent-api-keys", "test-credentials"]
# Job creation for test runs
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "delete"]
# Event logging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---
# RBAC Role for GitHub Actions Security Scanning
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-actions-security
  namespace: act-placemat
  labels:
    component: workload-identity
    data-residency: australia
  annotations:
    description: "Role for GitHub Actions security scanning operations"
    compliance.framework: "australian-privacy-act"
rules:
# Read access for security scanning
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch"]
# Security scan result storage
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "update", "patch"]
  resourceNames: ["security-scan-*", "vulnerability-report-*"]
# Event logging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---
# Role Bindings for GitHub Actions Service Accounts
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions-deploy-binding
  namespace: act-placemat
  labels:
    component: workload-identity
    data-residency: australia
  annotations:
    description: "Binds github-actions-deploy to deployment role"
    compliance.framework: "australian-privacy-act"
subjects:
- kind: ServiceAccount
  name: github-actions-deploy
  namespace: act-placemat
roleRef:
  kind: Role
  name: github-actions-deploy
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions-test-binding
  namespace: act-placemat
  labels:
    component: workload-identity
    data-residency: australia
  annotations:
    description: "Binds github-actions-test to testing role"
    compliance.framework: "australian-privacy-act"
subjects:
- kind: ServiceAccount
  name: github-actions-test
  namespace: act-placemat
roleRef:
  kind: Role
  name: github-actions-test
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions-security-binding
  namespace: act-placemat
  labels:
    component: workload-identity
    data-residency: australia
  annotations:
    description: "Binds github-actions-security to security scanning role"
    compliance.framework: "australian-privacy-act"
subjects:
- kind: ServiceAccount
  name: github-actions-security
  namespace: act-placemat
roleRef:
  kind: Role
  name: github-actions-security
  apiGroup: rbac.authorization.k8s.io

---
# Workload Identity Federation Monitoring ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: wif-monitoring-config
  namespace: act-placemat
  labels:
    component: workload-identity
    data-residency: australia
  annotations:
    description: "Monitoring configuration for Workload Identity Federation"
    compliance.framework: "australian-privacy-act"
data:
  monitoring_config: |
    # Metrics to collect
    metrics:
      - "workload_identity_token_requests_total"
      - "workload_identity_token_failures_total"
      - "workload_identity_token_duration_seconds"
      - "github_actions_workflow_runs_total"
      - "github_actions_workflow_failures_total"
      - "github_actions_deployment_duration_seconds"
    
    # Alert thresholds
    alerts:
      token_failure_rate: "5%"
      unusual_token_requests: "100/hour"
      failed_deployments: "3/hour"
      long_running_workflows: "60_minutes"
    
    # Audit requirements
    audit:
      log_all_token_requests: true
      log_attribute_mappings: true
      log_failed_authentications: true
      retention_period: "7_years"

  # GitHub Actions workflow templates
  github_workflows: |
    # Deployment workflow example
    deploy_workflow:
      name: "Deploy to Production"
      triggers: ["push to main", "manual dispatch"]
      jobs:
        - authenticate_gcp
        - build_and_push_images
        - deploy_to_kubernetes
        - run_smoke_tests
        - notify_completion
    
    # Testing workflow example  
    test_workflow:
      name: "Run Tests"
      triggers: ["pull request", "push to feature/*"]
      jobs:
        - authenticate_gcp
        - run_unit_tests
        - run_integration_tests
        - security_scan
        - upload_test_results
    
    # Security scan workflow
    security_workflow:
      name: "Security Scan"
      triggers: ["schedule: daily", "workflow dispatch"]
      jobs:
        - authenticate_gcp
        - container_image_scan
        - dependency_scan
        - sast_scan
        - infrastructure_scan
        - compliance_check