# Automated Rollback Configuration for ACT Placemat
# Implements intelligent rollback triggers based on performance and cultural protocol violations

apiVersion: batch/v1
kind: CronJob
metadata:
  name: canary-health-monitor
  namespace: act-placemat-production
  labels:
    app: act-placemat
    component: rollback-automation
spec:
  schedule: "*/1 * * * *" # Run every minute during canary deployments
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: canary-health-monitor
        spec:
          serviceAccountName: canary-health-monitor
          restartPolicy: OnFailure
          containers:
          - name: health-monitor
            image: act-placemat/health-monitor:latest
            env:
            - name: PROMETHEUS_URL
              value: "http://prometheus:9090"
            - name: ARGO_ROLLOUTS_URL
              value: "http://argo-rollouts-server:8080"
            - name: ELDER_COUNCIL_API_URL
              value: "http://elder-council-service:8080"
            - name: CULTURAL_PROTOCOL_API_URL
              value: "http://cultural-protocol-service:8080"
            - name: ROLLBACK_THRESHOLD_ERROR_RATE
              value: "0.05" # 5% error rate triggers rollback
            - name: ROLLBACK_THRESHOLD_CULTURAL_VIOLATIONS
              value: "1" # Any cultural violation triggers rollback
            - name: ROLLBACK_THRESHOLD_RESPONSE_TIME
              value: "2000" # 2s response time triggers rollback
            command:
            - "/bin/sh"
            - "-c"
            args:
            - |
              #!/bin/sh
              set -e
              
              echo "Starting canary health monitoring..."
              
              # Function to check if canary deployment is active
              check_canary_active() {
                kubectl get rollout act-placemat-canary -o jsonpath='{.status.phase}' | grep -q "Progressing\|Paused"
              }
              
              # Function to get current canary weight
              get_canary_weight() {
                kubectl get rollout act-placemat-canary -o jsonpath='{.status.canaryStatus.canaryWeight}' || echo "0"
              }
              
              # Function to trigger rollback
              trigger_rollback() {
                local reason="$1"
                echo "CRITICAL: Triggering rollback due to: $reason"
                
                # Trigger immediate rollback
                kubectl argo rollouts abort act-placemat-canary
                
                # Send emergency notifications
                curl -X POST "$CULTURAL_PROTOCOL_API_URL/emergency-notifications" \
                  -H "Content-Type: application/json" \
                  -d "{\"type\":\"rollback\",\"reason\":\"$reason\",\"timestamp\":\"$(date -Iseconds)\"}"
                
                # Log rollback event
                kubectl create event --namespace=act-placemat-production \
                  --reason="AutomatedRollback" \
                  --message="Automated rollback triggered: $reason" \
                  --reporting-controller="canary-health-monitor" \
                  --type="Warning" \
                  --involved-object-kind="Rollout" \
                  --involved-object-name="act-placemat-canary"
                
                exit 1
              }
              
              # Function to check Elder Council approval status
              check_elder_approval() {
                local weight="$1"
                # Elder approval required at 50% weight
                if [ "$weight" -ge 50 ]; then
                  local approval_status=$(kubectl get rollout act-placemat-canary -o jsonpath='{.metadata.annotations.cultural\.act\.place/elder-approved}' 2>/dev/null || echo "false")
                  if [ "$approval_status" != "true" ]; then
                    echo "WARNING: Elder approval required for weight $weight%, pausing deployment"
                    kubectl argo rollouts pause act-placemat-canary
                    
                    # Send notification to Elder Council
                    curl -X POST "$ELDER_COUNCIL_API_URL/approval-requests" \
                      -H "Content-Type: application/json" \
                      -d "{\"deployment\":\"act-placemat-canary\",\"weight\":$weight,\"timestamp\":\"$(date -Iseconds)\"}"
                  fi
                fi
              }
              
              # Check if canary deployment is active
              if ! check_canary_active; then
                echo "No active canary deployment found, exiting"
                exit 0
              fi
              
              CANARY_WEIGHT=$(get_canary_weight)
              echo "Current canary weight: $CANARY_WEIGHT%"
              
              # Check Elder Council approval requirements
              check_elder_approval "$CANARY_WEIGHT"
              
              # Query Prometheus for health metrics
              PROM_QUERY_BASE="$PROMETHEUS_URL/api/v1/query"
              
              # 1. Check error rate
              ERROR_RATE_QUERY="sum(rate(http_requests_total{service=\"act-placemat-canary\",code=~\"5..\"}[2m]))/sum(rate(http_requests_total{service=\"act-placemat-canary\"}[2m]))"
              ERROR_RATE=$(curl -s "$PROM_QUERY_BASE?query=$(echo "$ERROR_RATE_QUERY" | sed 's/ /%20/g')" | \
                jq -r '.data.result[0].value[1] // "0"')
              
              echo "Current error rate: $ERROR_RATE"
              
              if [ "$(echo "$ERROR_RATE > $ROLLBACK_THRESHOLD_ERROR_RATE" | bc -l)" -eq 1 ]; then
                trigger_rollback "High error rate: $ERROR_RATE (threshold: $ROLLBACK_THRESHOLD_ERROR_RATE)"
              fi
              
              # 2. Check cultural protocol violations
              VIOLATIONS_QUERY="sum(increase(cultural_protocol_violations_total{service=\"act-placemat-canary\"}[5m]))"
              VIOLATIONS=$(curl -s "$PROM_QUERY_BASE?query=$(echo "$VIOLATIONS_QUERY" | sed 's/ /%20/g')" | \
                jq -r '.data.result[0].value[1] // "0"')
              
              echo "Cultural violations in last 5min: $VIOLATIONS"
              
              if [ "$(echo "$VIOLATIONS >= $ROLLBACK_THRESHOLD_CULTURAL_VIOLATIONS" | bc -l)" -eq 1 ]; then
                trigger_rollback "Cultural protocol violations: $VIOLATIONS"
              fi
              
              # 3. Check response time (95th percentile)
              RESPONSE_TIME_QUERY="histogram_quantile(0.95,sum(rate(http_request_duration_seconds_bucket{service=\"act-placemat-canary\"}[2m]))by(le))*1000"
              RESPONSE_TIME=$(curl -s "$PROM_QUERY_BASE?query=$(echo "$RESPONSE_TIME_QUERY" | sed 's/ /%20/g')" | \
                jq -r '.data.result[0].value[1] // "0"')
              
              echo "95th percentile response time: ${RESPONSE_TIME}ms"
              
              if [ "$(echo "$RESPONSE_TIME > $ROLLBACK_THRESHOLD_RESPONSE_TIME" | bc -l)" -eq 1 ]; then
                trigger_rollback "High response time: ${RESPONSE_TIME}ms (threshold: ${ROLLBACK_THRESHOLD_RESPONSE_TIME}ms)"
              fi
              
              # 4. Check cultural compliance rate
              COMPLIANCE_QUERY="sum(rate(cultural_protocol_events_total{service=\"act-placemat-canary\",status=\"approved\"}[5m]))/sum(rate(cultural_protocol_events_total{service=\"act-placemat-canary\"}[5m]))"
              COMPLIANCE_RATE=$(curl -s "$PROM_QUERY_BASE?query=$(echo "$COMPLIANCE_QUERY" | sed 's/ /%20/g')" | \
                jq -r '.data.result[0].value[1] // "1"')
              
              echo "Cultural compliance rate: $COMPLIANCE_RATE"
              
              if [ "$(echo "$COMPLIANCE_RATE < 0.85" | bc -l)" -eq 1 ]; then
                trigger_rollback "Low cultural compliance rate: $COMPLIANCE_RATE (minimum: 0.85)"
              fi
              
              # 5. Check community engagement impact
              ENGAGEMENT_QUERY="sum(rate(community_interactions_total{deployment=\"canary\"}[5m]))"
              ENGAGEMENT_RATE=$(curl -s "$PROM_QUERY_BASE?query=$(echo "$ENGAGEMENT_QUERY" | sed 's/ /%20/g')" | \
                jq -r '.data.result[0].value[1] // "0"')
              
              # Compare with stable deployment engagement
              STABLE_ENGAGEMENT_QUERY="sum(rate(community_interactions_total{deployment=\"stable\"}[5m]))"
              STABLE_ENGAGEMENT=$(curl -s "$PROM_QUERY_BASE?query=$(echo "$STABLE_ENGAGEMENT_QUERY" | sed 's/ /%20/g')" | \
                jq -r '.data.result[0].value[1] // "1"')
              
              if [ "$(echo "$STABLE_ENGAGEMENT > 0" | bc -l)" -eq 1 ]; then
                ENGAGEMENT_RATIO=$(echo "scale=2; $ENGAGEMENT_RATE / $STABLE_ENGAGEMENT" | bc -l)
                echo "Community engagement ratio (canary/stable): $ENGAGEMENT_RATIO"
                
                if [ "$(echo "$ENGAGEMENT_RATIO < 0.7" | bc -l)" -eq 1 ]; then
                  trigger_rollback "Significant drop in community engagement: $ENGAGEMENT_RATIO (minimum: 0.7)"
                fi
              fi
              
              echo "All health checks passed for canary deployment"
              
              # Update health status annotation
              kubectl annotate rollout act-placemat-canary \
                "health.act.place/last-check=$(date -Iseconds)" \
                "health.act.place/status=healthy" \
                "health.act.place/error-rate=$ERROR_RATE" \
                "health.act.place/cultural-violations=$VIOLATIONS" \
                "health.act.place/response-time=$RESPONSE_TIME" \
                "health.act.place/compliance-rate=$COMPLIANCE_RATE" \
                --overwrite

---
# ServiceAccount and RBAC for Health Monitor
apiVersion: v1
kind: ServiceAccount
metadata:
  name: canary-health-monitor
  namespace: act-placemat-production

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: canary-health-monitor
  namespace: act-placemat-production
rules:
- apiGroups: ["argoproj.io"]
  resources: ["rollouts"]
  verbs: ["get", "list", "patch", "update"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: canary-health-monitor
  namespace: act-placemat-production
subjects:
- kind: ServiceAccount
  name: canary-health-monitor
  namespace: act-placemat-production
roleRef:
  kind: Role
  name: canary-health-monitor
  apiGroup: rbac.authorization.k8s.io

---
# Emergency Rollback Webhook Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emergency-rollback-webhook
  namespace: act-placemat-production
  labels:
    app: emergency-rollback-webhook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emergency-rollback-webhook
  template:
    metadata:
      labels:
        app: emergency-rollback-webhook
    spec:
      serviceAccountName: canary-health-monitor
      containers:
      - name: webhook
        image: act-placemat/rollback-webhook:latest
        ports:
        - containerPort: 8080
        env:
        - name: ARGO_ROLLOUTS_URL
          value: "http://argo-rollouts-server:8080"
        - name: CULTURAL_PROTOCOL_API_URL
          value: "http://cultural-protocol-service:8080"
        - name: ELDER_COUNCIL_API_URL
          value: "http://elder-council-service:8080"
        command:
        - "/bin/sh"
        - "-c"
        args:
        - |
          #!/bin/sh
          
          cat > /app/server.js << 'EOF'
          const express = require('express');
          const { exec } = require('child_process');
          const app = express();
          
          app.use(express.json());
          
          // Health check endpoint
          app.get('/health', (req, res) => {
            res.json({ status: 'healthy', timestamp: new Date().toISOString() });
          });
          
          // Emergency rollback endpoint
          app.post('/rollback', (req, res) => {
            const { reason, triggeredBy } = req.body;
            
            console.log(`Emergency rollback triggered by ${triggeredBy}: ${reason}`);
            
            // Execute rollback
            exec('kubectl argo rollouts abort act-placemat-canary', (error, stdout, stderr) => {
              if (error) {
                console.error('Rollback failed:', error);
                res.status(500).json({ error: 'Rollback failed', details: error.message });
                return;
              }
              
              console.log('Rollback successful:', stdout);
              
              // Notify cultural protocol service
              const notificationPayload = {
                type: 'emergency-rollback',
                reason: reason,
                triggeredBy: triggeredBy,
                timestamp: new Date().toISOString(),
                rollbackOutput: stdout
              };
              
              // Send notifications (simplified for example)
              console.log('Sending emergency notifications:', notificationPayload);
              
              res.json({ 
                success: true, 
                message: 'Emergency rollback completed',
                details: stdout
              });
            });
          });
          
          // Cultural protocol violation handler
          app.post('/cultural-violation', (req, res) => {
            const { violationType, severity, details } = req.body;
            
            console.log('Cultural violation detected:', { violationType, severity, details });
            
            if (severity === 'critical') {
              // Immediate rollback for critical violations
              exec('kubectl argo rollouts abort act-placemat-canary', (error, stdout) => {
                if (!error) {
                  console.log('Immediate rollback due to critical cultural violation');
                }
              });
            } else if (severity === 'high') {
              // Pause deployment for Elder Council review
              exec('kubectl argo rollouts pause act-placemat-canary', (error, stdout) => {
                if (!error) {
                  console.log('Deployment paused for Elder Council review');
                }
              });
            }
            
            res.json({ success: true, action: severity === 'critical' ? 'rollback' : 'pause' });
          });
          
          // Elder Council decision endpoint
          app.post('/elder-decision', (req, res) => {
            const { decision, elderId, comments } = req.body;
            
            console.log(`Elder Council decision by ${elderId}: ${decision}`);
            
            if (decision === 'approve') {
              // Add approval annotation and resume
              const annotationCmd = `kubectl annotate rollout act-placemat-canary cultural.act.place/elder-approved=true cultural.act.place/elder-id=${elderId} cultural.act.place/approval-timestamp=$(date -Iseconds) --overwrite`;
              
              exec(annotationCmd, (error) => {
                if (!error) {
                  exec('kubectl argo rollouts unpause act-placemat-canary', (unpauseError) => {
                    if (!unpauseError) {
                      console.log('Deployment resumed after Elder approval');
                    }
                  });
                }
              });
              
              res.json({ success: true, action: 'approved-and-resumed' });
            } else {
              // Reject and rollback
              exec('kubectl argo rollouts abort act-placemat-canary', (error) => {
                if (!error) {
                  console.log('Deployment rolled back after Elder rejection');
                }
              });
              
              res.json({ success: true, action: 'rejected-and-rolled-back' });
            }
          });
          
          const PORT = process.env.PORT || 8080;
          app.listen(PORT, () => {
            console.log(`Emergency rollback webhook listening on port ${PORT}`);
          });
          EOF
          
          # Install dependencies and start server
          npm init -y
          npm install express
          node /app/server.js
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: emergency-rollback-webhook
  namespace: act-placemat-production
spec:
  selector:
    app: emergency-rollback-webhook
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP

---
# NetworkPolicy to secure webhook access
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: emergency-rollback-webhook-policy
  namespace: act-placemat-production
spec:
  podSelector:
    matchLabels:
      app: emergency-rollback-webhook
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: cultural-protocol-service
    - podSelector:
        matchLabels:
          app: elder-council-service
    - podSelector:
        matchLabels:
          app: prometheus
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: argo-rollouts-server
    ports:
    - protocol: TCP
      port: 8080
  - to: []
    ports:
    - protocol: TCP
      port: 443 # For Kubernetes API
    - protocol: TCP
      port: 6443 # Alternative Kubernetes API port