# LangGraph Base Services for ACT Placemat Intelligence Hub
# Australian-compliant foundation services for multi-agent framework

---
# LangGraph State Store ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: langgraph-config
  namespace: act-placemat
  labels:
    component: langgraph
    data-residency: australia
  annotations:
    description: "LangGraph framework configuration"
    compliance.framework: "australian-privacy-act"
data:
  # LangGraph Configuration
  langgraph_version: "0.2.0"
  checkpoint_driver: "postgresql"
  state_store_type: "redis"
  agent_discovery: "kubernetes"
  workflow_engine: "async"
  
  # Australian Compliance Settings
  data_residency: "australia"
  compliance_framework: "australian-privacy-act"
  audit_logging: "enabled"
  encryption_required: "true"
  
  # Database Configuration
  postgres_host: "postgres"
  postgres_port: "5432"
  postgres_database: "act_placemat_intelligence"
  postgres_schema: "langgraph"
  
  # Redis Configuration
  redis_host: "redis"
  redis_port: "6379"
  redis_database: "3"
  
  # Agent Configuration
  agent_timeout: "300"
  max_concurrent_agents: "10"
  agent_retry_attempts: "3"
  
  # Workflow Configuration
  max_workflow_steps: "50"
  workflow_timeout: "1800"
  checkpoint_interval: "30"
  
  # Australian Timezone and Locale
  timezone: "Australia/Sydney"
  locale: "en-AU"
  currency: "AUD"

---
# LangGraph Secrets
apiVersion: v1
kind: Secret
metadata:
  name: langgraph-secrets
  namespace: act-placemat
  labels:
    component: langgraph
    data-residency: australia
  annotations:
    description: "LangGraph framework secrets"
    compliance.framework: "australian-privacy-act"
    data.classification: "confidential"
    audit.required: "true"
type: Opaque
data:
  # Database credentials (base64 encoded)
  postgres_username: ${POSTGRES_USERNAME_B64}
  postgres_password: ${POSTGRES_PASSWORD_B64}
  
  # Redis credentials
  redis_password: ${REDIS_PASSWORD_B64}
  
  # LangGraph encryption keys
  state_encryption_key: ${LANGGRAPH_STATE_KEY_B64}
  checkpoint_encryption_key: ${LANGGRAPH_CHECKPOINT_KEY_B64}
  
  # AI Model API Keys
  openai_api_key: ${OPENAI_API_KEY_B64}
  anthropic_api_key: ${ANTHROPIC_API_KEY_B64}
  
  # Australian compliance keys
  audit_signing_key: ${AUDIT_SIGNING_KEY_B64}
  compliance_token: ${COMPLIANCE_TOKEN_B64}

---
# LangGraph State Store Service
apiVersion: v1
kind: Service
metadata:
  name: langgraph-state-store
  namespace: act-placemat
  labels:
    app: langgraph
    component: state-store
    data-residency: australia
  annotations:
    description: "LangGraph state store service"
    compliance.framework: "australian-privacy-act"
spec:
  selector:
    app: langgraph
    component: state-store
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  - name: metrics
    port: 9121
    targetPort: 9121
    protocol: TCP
  type: ClusterIP

---
# LangGraph Checkpoint Store Service
apiVersion: v1
kind: Service
metadata:
  name: langgraph-checkpoint-store
  namespace: act-placemat
  labels:
    app: langgraph
    component: checkpoint-store
    data-residency: australia
  annotations:
    description: "LangGraph checkpoint store service"
    compliance.framework: "australian-privacy-act"
spec:
  selector:
    app: postgres
    component: database
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP

---
# LangGraph Agent Registry Service
apiVersion: v1
kind: Service
metadata:
  name: langgraph-agent-registry
  namespace: act-placemat
  labels:
    app: langgraph
    component: agent-registry
    data-residency: australia
  annotations:
    description: "LangGraph agent registry and discovery service"
    compliance.framework: "australian-privacy-act"
spec:
  selector:
    app: intelligence-hub
    component: orchestrator
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP

---
# LangGraph Workflow Engine Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: langgraph-workflow-engine
  namespace: act-placemat
  labels:
    app: langgraph
    component: workflow-engine
    data-residency: australia
  annotations:
    description: "LangGraph workflow execution engine"
    compliance.framework: "australian-privacy-act"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: langgraph
      component: workflow-engine
  template:
    metadata:
      labels:
        app: langgraph
        component: workflow-engine
        data-residency: australia
      annotations:
        compliance.framework: "australian-privacy-act"
        data.classification: "internal"
    spec:
      serviceAccountName: intelligence-hub
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: workflow-engine
        image: registry.actplacemat.org.au:5000/act-placemat/langgraph-engine:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: TZ
          value: "Australia/Sydney"
        - name: LANGGRAPH_ENV
          value: "production"
        - name: DATA_RESIDENCY
          valueFrom:
            configMapKeyRef:
              name: australian-compliance-config
              key: DATA_RESIDENCY
        - name: COMPLIANCE_FRAMEWORK
          valueFrom:
            configMapKeyRef:
              name: australian-compliance-config
              key: COMPLIANCE_FRAMEWORK
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: langgraph-config
              key: postgres_host
        - name: POSTGRES_DATABASE
          valueFrom:
            configMapKeyRef:
              name: langgraph-config
              key: postgres_database
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: langgraph-secrets
              key: postgres_username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: langgraph-secrets
              key: postgres_password
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: langgraph-config
              key: redis_host
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: langgraph-secrets
              key: redis_password
        - name: STATE_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: langgraph-secrets
              key: state_encryption_key
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: config
          mountPath: /app/config
          readOnly: true
        - name: compliance-config
          mountPath: /app/compliance
          readOnly: true
      volumes:
      - name: tmp
        emptyDir: {}
      - name: config
        configMap:
          name: langgraph-config
      - name: compliance-config
        configMap:
          name: australian-compliance-config
      imagePullSecrets:
      - name: registry-credentials
      nodeSelector:
        kubernetes.io/os: linux
        data-residency: australia
      tolerations:
      - key: "data-residency"
        operator: "Equal"
        value: "australia"
        effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - langgraph
                - key: component
                  operator: In
                  values:
                  - workflow-engine
              topologyKey: kubernetes.io/hostname

---
# LangGraph Agent Template Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: langgraph-agent-template
  namespace: act-placemat
  labels:
    app: langgraph
    component: agent-template
    data-residency: australia
  annotations:
    description: "Template deployment for LangGraph agents"
    compliance.framework: "australian-privacy-act"
spec:
  replicas: 0  # Template only, scaled by orchestrator
  selector:
    matchLabels:
      app: langgraph
      component: agent
  template:
    metadata:
      labels:
        app: langgraph
        component: agent
        data-residency: australia
      annotations:
        compliance.framework: "australian-privacy-act"
        data.classification: "internal"
    spec:
      serviceAccountName: financial-intelligence-agent  # Default, overridden per agent
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: agent
        image: registry.actplacemat.org.au:5000/act-placemat/langgraph-agent:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: TZ
          value: "Australia/Sydney"
        - name: AGENT_TYPE
          value: "template"  # Overridden per agent
        - name: DATA_RESIDENCY
          valueFrom:
            configMapKeyRef:
              name: australian-compliance-config
              key: DATA_RESIDENCY
        - name: COMPLIANCE_FRAMEWORK
          valueFrom:
            configMapKeyRef:
              name: australian-compliance-config
              key: COMPLIANCE_FRAMEWORK
        - name: LANGGRAPH_CHECKPOINT_STORE
          value: "postgresql://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):5432/$(POSTGRES_DATABASE)"
        - name: LANGGRAPH_STATE_STORE
          value: "redis://$(REDIS_HOST):6379/3"
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: langgraph-config
              key: postgres_host
        - name: POSTGRES_DATABASE
          valueFrom:
            configMapKeyRef:
              name: langgraph-config
              key: postgres_database
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: langgraph-secrets
              key: postgres_username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: langgraph-secrets
              key: postgres_password
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: langgraph-config
              key: redis_host
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: langgraph-secrets
              key: redis_password
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: langgraph-secrets
              key: openai_api_key
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: langgraph-secrets
              key: anthropic_api_key
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: agent-config
          mountPath: /app/config
          readOnly: true
        - name: compliance-config
          mountPath: /app/compliance
          readOnly: true
      volumes:
      - name: tmp
        emptyDir: {}
      - name: agent-config
        configMap:
          name: langgraph-config
      - name: compliance-config
        configMap:
          name: australian-compliance-config
      imagePullSecrets:
      - name: registry-credentials
      nodeSelector:
        kubernetes.io/os: linux
        data-residency: australia
      tolerations:
      - key: "data-residency"
        operator: "Equal"
        value: "australia"
        effect: "NoSchedule"

---
# LangGraph Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: langgraph-workflow-engine-hpa
  namespace: act-placemat
  labels:
    app: langgraph
    component: workflow-engine
    data-residency: australia
  annotations:
    description: "HPA for LangGraph workflow engine"
    compliance.framework: "australian-privacy-act"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: langgraph-workflow-engine
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max

---
# LangGraph Service Monitor for Prometheus
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: langgraph-metrics
  namespace: act-placemat
  labels:
    app: langgraph
    data-residency: australia
  annotations:
    description: "Prometheus service monitor for LangGraph metrics"
    compliance.framework: "australian-privacy-act"
spec:
  selector:
    matchLabels:
      app: langgraph
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    honorLabels: true
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_label_data_residency]
      targetLabel: data_residency
    - sourceLabels: [__meta_kubernetes_pod_annotation_compliance_framework]
      targetLabel: compliance_framework