-- Create table for storing business agent insights
CREATE TABLE IF NOT EXISTS agent_insights (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_name TEXT NOT NULL,
  agent_version TEXT NOT NULL,
  insights JSONB NOT NULL,
  recommendations JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

  -- Indexes for better query performance
  CONSTRAINT agent_insights_pkey PRIMARY KEY (id)
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_agent_insights_created_at
  ON agent_insights(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_agent_insights_agent_name
  ON agent_insights(agent_name);

-- Add row level security (RLS)
ALTER TABLE agent_insights ENABLE ROW LEVEL SECURITY;

-- Policy: Allow all operations for authenticated users (admin/co-founders only)
CREATE POLICY agent_insights_all ON agent_insights
  FOR ALL
  USING (auth.role() = 'authenticated');

-- Add helpful comment
COMMENT ON TABLE agent_insights IS
  'Stores historical insights and recommendations from the Business Agent for Australia.
   Used for tracking agent performance, generating reports, and historical analysis.';

COMMENT ON COLUMN agent_insights.insights IS
  'JSONB containing structured insights across domains: financial, compliance, opportunities, relationships, projects';

COMMENT ON COLUMN agent_insights.recommendations IS
  'JSONB containing prioritized actionable recommendations generated by the agent';