# Australian Compliance Custom Roles for ACT Placemat Intelligence Hub
# Specialized roles ensuring Australian Privacy Act 1988 compliance

---
# Australian Data Protection Officer Role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: australian-data-protection-officer
  labels:
    component: compliance
    data-residency: australia
    privilege-level: compliance
  annotations:
    description: "Data Protection Officer role for Australian Privacy Act compliance"
    compliance.framework: "australian-privacy-act"
    data.classification: "restricted"
    last.reviewed: "2024-08-15"
    next.review: "2025-02-15"
rules:
# Read-only access to all resources for compliance assessment
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["policy"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
# Create compliance reports and audit findings
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "update", "patch"]
  resourceNames: ["compliance-report-*", "privacy-assessment-*", "data-audit-*"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
# Compliance violation enforcement
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete"]
  resourceNames: ["non-compliant-*"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["patch", "update"]
  resourceNames: ["non-compliant-*"]

---
# Australian Data Residency Enforcer Role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: australian-data-residency-enforcer
  labels:
    component: compliance
    data-residency: australia
    privilege-level: enforcement
  annotations:
    description: "Enforces Australian data residency requirements"
    compliance.framework: "australian-privacy-act"
    data.classification: "restricted"
rules:
# Node and zone management for data residency
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: [""]
  resources: ["persistentvolumes", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
# Pod scheduling control for Australian zones
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
  verbs: ["get", "list", "watch", "patch", "update"]
# Network policy enforcement
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Event logging for enforcement actions
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]

---
# Australian Privacy Impact Assessor Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: australian-privacy-impact-assessor
  namespace: act-placemat
  labels:
    component: compliance
    data-residency: australia
    privilege-level: assessment
  annotations:
    description: "Conducts Privacy Impact Assessments for Australian compliance"
    compliance.framework: "australian-privacy-act"
    data.classification: "confidential"
rules:
# Read access for privacy impact assessment
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
  resourceNames: ["*privacy*", "*compliance*", "*audit*", "*classification*"]
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
# Create privacy impact assessments
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "update", "patch"]
  resourceNames: ["privacy-impact-*", "data-flow-analysis-*", "risk-assessment-*"]
# Event logging for assessments
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---
# Australian Audit Trail Manager Role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: australian-audit-trail-manager
  labels:
    component: compliance
    data-residency: australia
    privilege-level: audit
  annotations:
    description: "Manages audit trails for Australian compliance requirements"
    compliance.framework: "australian-privacy-act"
    data.classification: "restricted"
rules:
# Read-only access for audit trail collection
- apiGroups: [""]
  resources: ["events", "pods", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
  verbs: ["get", "list", "watch"]
# Create and manage audit logs
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "update", "patch"]
  resourceNames: ["audit-log-*", "access-log-*", "security-event-*"]
# Event creation for audit trail
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
# Job management for audit processing
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]

---
# Australian Key Custodian Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: australian-key-custodian
  namespace: act-placemat
  labels:
    component: compliance
    data-residency: australia
    privilege-level: key-management
  annotations:
    description: "Custodian role for encryption keys under Australian compliance"
    compliance.framework: "australian-privacy-act"
    data.classification: "restricted"
    audit.enhanced: "true"
rules:
# Restricted access to encryption keys
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
  resourceNames: ["cmek-*", "encryption-*", "ca-*", "audit-signing-*"]
# Key rotation and management
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "update", "patch"]
  resourceNames: ["cmek-*", "encryption-*", "backup-encryption-*"]
# Key usage audit logging
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "update", "patch"]
  resourceNames: ["key-usage-log-*", "key-rotation-log-*"]
# Event logging for key operations
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---
# Australian Incident Response Role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: australian-incident-response
  labels:
    component: compliance
    data-residency: australia
    privilege-level: incident-response
  annotations:
    description: "Incident response role for Australian compliance violations"
    compliance.framework: "australian-privacy-act"
    data.classification: "restricted"
    emergency.access: "true"
rules:
# Emergency read access
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
# Emergency containment actions
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["patch", "update", "scale"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["create", "update", "patch"]
# Incident documentation
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "update", "patch"]
  resourceNames: ["incident-*", "breach-*", "violation-*"]
# Event creation for incident tracking
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]

---
# Australian Backup Compliance Manager Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: australian-backup-compliance-manager
  namespace: act-placemat
  labels:
    component: compliance
    data-residency: australia
    privilege-level: backup-compliance
  annotations:
    description: "Manages backup compliance for Australian data retention requirements"
    compliance.framework: "australian-privacy-act"
    data.classification: "confidential"
rules:
# Backup storage management
- apiGroups: [""]
  resources: ["persistentvolumes", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "patch"]
  resourceNames: ["backup-*", "archive-*"]
# Backup configuration management
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
  resourceNames: ["backup-config", "retention-policy", "backup-compliance-*"]
# Backup job management
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
  resourceNames: ["backup-*", "retention-*"]
# Event logging for backup compliance
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---
# Service Account for Australian Data Protection Officer
apiVersion: v1
kind: ServiceAccount
metadata:
  name: australian-data-protection-officer
  namespace: act-placemat
  labels:
    component: compliance
    role: data-protection-officer
    data-residency: australia
  annotations:
    description: "Service account for Australian Data Protection Officer"
    compliance.framework: "australian-privacy-act"
    data.classification: "restricted"
    audit.required: "true"
automountServiceAccountToken: true

---
# ClusterRoleBinding for Data Protection Officer
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: australian-data-protection-officer-binding
  labels:
    component: compliance
    data-residency: australia
  annotations:
    description: "Binds Data Protection Officer to compliance role"
    compliance.framework: "australian-privacy-act"
subjects:
- kind: ServiceAccount
  name: australian-data-protection-officer
  namespace: act-placemat
roleRef:
  kind: ClusterRole
  name: australian-data-protection-officer
  apiGroup: rbac.authorization.k8s.io

---
# Service Account for Data Residency Enforcer
apiVersion: v1
kind: ServiceAccount
metadata:
  name: australian-data-residency-enforcer
  namespace: act-placemat
  labels:
    component: compliance
    role: data-residency-enforcer
    data-residency: australia
  annotations:
    description: "Service account for Australian Data Residency Enforcer"
    compliance.framework: "australian-privacy-act"
    data.classification: "restricted"
    audit.required: "true"
automountServiceAccountToken: true

---
# ClusterRoleBinding for Data Residency Enforcer
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: australian-data-residency-enforcer-binding
  labels:
    component: compliance
    data-residency: australia
  annotations:
    description: "Binds Data Residency Enforcer to enforcement role"
    compliance.framework: "australian-privacy-act"
subjects:
- kind: ServiceAccount
  name: australian-data-residency-enforcer
  namespace: act-placemat
roleRef:
  kind: ClusterRole
  name: australian-data-residency-enforcer
  apiGroup: rbac.authorization.k8s.io

---
# Service Account for Privacy Impact Assessor
apiVersion: v1
kind: ServiceAccount
metadata:
  name: australian-privacy-impact-assessor
  namespace: act-placemat
  labels:
    component: compliance
    role: privacy-impact-assessor
    data-residency: australia
  annotations:
    description: "Service account for Australian Privacy Impact Assessor"
    compliance.framework: "australian-privacy-act"
    data.classification: "confidential"
    audit.required: "true"
automountServiceAccountToken: true

---
# RoleBinding for Privacy Impact Assessor
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: australian-privacy-impact-assessor-binding
  namespace: act-placemat
  labels:
    component: compliance
    data-residency: australia
  annotations:
    description: "Binds Privacy Impact Assessor to assessment role"
    compliance.framework: "australian-privacy-act"
subjects:
- kind: ServiceAccount
  name: australian-privacy-impact-assessor
  namespace: act-placemat
roleRef:
  kind: Role
  name: australian-privacy-impact-assessor
  apiGroup: rbac.authorization.k8s.io

---
# Compliance Role Templates ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: australian-compliance-role-templates
  namespace: act-placemat
  labels:
    component: compliance
    data-residency: australia
  annotations:
    description: "Templates for creating additional Australian compliance roles"
    compliance.framework: "australian-privacy-act"
data:
  time_based_compliance_role_template: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: ROLE_NAME-time-limited
      namespace: act-placemat
      labels:
        component: compliance
        data-residency: australia
        privilege-level: time-limited
      annotations:
        description: "Time-limited compliance role"
        compliance.framework: "australian-privacy-act"
        valid.from: "REPLACE_WITH_START_TIME"
        valid.until: "REPLACE_WITH_END_TIME"
        granted.to: "REPLACE_WITH_USER_OR_SA"
        audit.enhanced: "true"
    rules:
    - apiGroups: [""]
      resources: ["configmaps"]
      verbs: ["get", "list", "watch"]
      resourceNames: ["compliance-*", "audit-*"]
    - apiGroups: [""]
      resources: ["events"]
      verbs: ["create"]

  emergency_compliance_role_template: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: ROLE_NAME-emergency-compliance
      labels:
        component: compliance
        data-residency: australia
        privilege-level: emergency
      annotations:
        description: "Emergency compliance role for incidents"
        compliance.framework: "australian-privacy-act"
        emergency.use.only: "true"
        approval.required: "true"
        audit.enhanced: "true"
    rules:
    - apiGroups: [""]
      resources: ["pods", "services"]
      verbs: ["get", "list", "watch", "delete", "patch"]
    - apiGroups: ["apps"]
      resources: ["deployments"]
      verbs: ["get", "list", "watch", "patch", "scale"]
    - apiGroups: [""]
      resources: ["events"]
      verbs: ["create", "patch"]