# Least-Privilege IAM Roles for ACT Placemat Intelligence Hub
# Australian-compliant role definitions with minimal required permissions

---
# Financial Intelligence Agent Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: financial-intelligence-least-privilege
  namespace: act-placemat
  labels:
    component: agent
    agent-type: financial-intelligence
    data-residency: australia
    privilege-level: least
  annotations:
    description: "Least-privilege role for Financial Intelligence Agent"
    compliance.framework: "australian-privacy-act"
    data.classification: "confidential"
    last.reviewed: "2024-08-15"
    next.review: "2024-11-15"
rules:
# Task queue access (read-only for tasks, write for results)
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
  resourceNames: ["task-queue-config", "financial-config"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "update", "patch"]
  resourceNames: ["financial-results-*"]
# Secrets access (specific financial API keys only)
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["financial-api-keys", "abn-lookup-credentials", "asic-api-keys", "xero-credentials"]
# Event logging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
# Self-monitoring
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
  resourceNames: ["self"]
# Metrics export
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
  resourceNames: ["financial-metrics"]

---
# Research Analyst Agent Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: research-analyst-least-privilege
  namespace: act-placemat
  labels:
    component: agent
    agent-type: research-analyst
    data-residency: australia
    privilege-level: least
  annotations:
    description: "Least-privilege role for Research Analyst Agent"
    compliance.framework: "australian-privacy-act"
    data.classification: "internal"
    last.reviewed: "2024-08-15"
    next.review: "2024-11-15"
rules:
# Task queue access
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
  resourceNames: ["task-queue-config", "research-config", "web-scraping-config"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "update", "patch"]
  resourceNames: ["research-results-*"]
# Research API keys
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["research-api-keys", "web-scraping-credentials", "notion-research-token"]
# Event logging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
# Limited job creation for research tasks
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list"]
  resourceNames: ["research-job-*"]

---
# Compliance Officer Agent Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: compliance-officer-least-privilege
  namespace: act-placemat
  labels:
    component: agent
    agent-type: compliance-officer
    data-residency: australia
    privilege-level: least
  annotations:
    description: "Least-privilege role for Compliance Officer Agent"
    compliance.framework: "australian-privacy-act"
    data.classification: "confidential"
    last.reviewed: "2024-08-15"
    next.review: "2024-11-15"
rules:
# Read-only access to audit and compliance data
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
  resourceNames: ["australian-compliance-config", "permissions-audit", "compliance-rules"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "update", "patch"]
  resourceNames: ["compliance-assessment-*", "privacy-impact-*"]
# Read-only access to system events for compliance monitoring
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "create"]
# Read-only access to pods and services for compliance auditing
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
# Read-only access to RBAC for compliance auditing
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "watch"]
# Read-only access to network policies
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch"]
# Compliance reporting secrets
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["compliance-reporting-credentials"]

---
# Community Coordinator Agent Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: community-coordinator-least-privilege
  namespace: act-placemat
  labels:
    component: agent
    agent-type: community-coordinator
    data-residency: australia
    privilege-level: least
  annotations:
    description: "Least-privilege role for Community Coordinator Agent"
    compliance.framework: "australian-privacy-act"
    data.classification: "community"
    last.reviewed: "2024-08-15"
    next.review: "2024-11-15"
rules:
# Community engagement configuration
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
  resourceNames: ["community-config", "democratic-voting", "consensus-state", "engagement-metrics"]
# Community API credentials
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["community-api-keys", "notification-credentials"]
# Event logging for community activities
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---
# Registry Management Role (Least Privilege)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: registry-manager-least-privilege
  namespace: act-placemat
  labels:
    component: registry
    data-residency: australia
    privilege-level: least
  annotations:
    description: "Least-privilege role for registry management"
    compliance.framework: "australian-privacy-act"
    data.classification: "operational"
rules:
# Registry configuration (read-only)
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
  resourceNames: ["registry-config", "image-pull-policy", "harbor-config"]
# Registry credentials (read-only)
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
  resourceNames: ["registry-credentials", "harbor-credentials"]
# Image scanning results
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "update", "patch"]
  resourceNames: ["vulnerability-scan-*", "image-metadata-*"]
# Event logging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---
# Monitoring Observer Role (Read-Only)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitoring-observer-least-privilege
  namespace: act-placemat
  labels:
    component: monitoring
    data-residency: australia
    privilege-level: least
  annotations:
    description: "Least-privilege read-only role for monitoring"
    compliance.framework: "australian-privacy-act"
    data.classification: "operational"
rules:
# Read-only access to pods and services
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "nodes"]
  verbs: ["get", "list", "watch"]
# Read-only access to metrics configuration
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
  resourceNames: ["monitoring-config", "prometheus-config", "grafana-config"]
# Read-only access to events
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
# Read-only access to deployments for monitoring
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
  verbs: ["get", "list", "watch"]

---
# Backup Operator Role (Least Privilege)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backup-operator-least-privilege
  namespace: act-placemat
  labels:
    component: backup
    data-residency: australia
    privilege-level: least
  annotations:
    description: "Least-privilege role for backup operations"
    compliance.framework: "australian-privacy-act"
    data.classification: "confidential"
rules:
# Read-only access to backup sources
- apiGroups: [""]
  resources: ["persistentvolumes", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
# Backup snapshot creation
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create"]
  resourceNames: ["backup-snapshot-*"]
# Backup configuration
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
  resourceNames: ["backup-config", "retention-policy"]
# Backup credentials (specific to backup operations)
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["backup-encryption-key", "backup-storage-credentials"]
# Job creation for backup operations
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create"]
  resourceNames: ["backup-job-*"]
# Event logging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---
# Australian Data Auditor Role (Compliance Read-Only)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: australian-data-auditor-least-privilege
  namespace: act-placemat
  labels:
    component: compliance
    data-residency: australia
    privilege-level: least
  annotations:
    description: "Least-privilege role for Australian data compliance auditing"
    compliance.framework: "australian-privacy-act"
    data.classification: "confidential"
    compliance.role: "auditor"
rules:
# Read-only access to all resources for auditing
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
# Read-only access to apps
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
# Read-only access to RBAC
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
# Read-only access to network policies
- apiGroups: ["networking.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
# Read-only access to policies
- apiGroups: ["policy"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
# Audit report creation
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create"]
  resourceNames: ["audit-report-*", "compliance-report-*"]
# Event creation for audit logging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---
# Time-Based Access Role Template
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: time-based-access-template
  namespace: act-placemat
  labels:
    component: temporary-access
    data-residency: australia
    privilege-level: temporary
  annotations:
    description: "Template for time-based access roles (requires manual instantiation)"
    compliance.framework: "australian-privacy-act"
    usage: "This role should be instantiated with specific time limits"
    valid.from: "REPLACE_WITH_START_TIME"
    valid.until: "REPLACE_WITH_END_TIME"
    granted.to: "REPLACE_WITH_USER_OR_SA"
rules:
# Emergency access (to be customized based on need)
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
# Event logging for temporary access
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---
# Agent Communication Role (Inter-Agent)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agent-communication-least-privilege
  namespace: act-placemat
  labels:
    component: inter-agent
    data-residency: australia
    privilege-level: least
  annotations:
    description: "Least-privilege role for inter-agent communication"
    compliance.framework: "australian-privacy-act"
    data.classification: "internal"
rules:
# Message queue access
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
  resourceNames: ["agent-communication-config", "message-routing"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "update", "patch"]
  resourceNames: ["agent-message-*", "workflow-state-*"]
# Communication credentials
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["agent-communication-token", "workflow-encryption-key"]
# Service discovery
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
# Event logging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---
# Emergency Access Role (Break-Glass)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: emergency-access-break-glass
  namespace: act-placemat
  labels:
    component: emergency
    data-residency: australia
    privilege-level: emergency
  annotations:
    description: "Emergency break-glass access role (requires approval and logging)"
    compliance.framework: "australian-privacy-act"
    data.classification: "restricted"
    emergency.use.only: "true"
    approval.required: "true"
    audit.enhanced: "true"
rules:
# Emergency pod access
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "patch", "delete"]
# Emergency service management
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "patch"]
# Emergency deployment management
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch", "scale"]
# Emergency event creation (with enhanced logging)
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
# Emergency configuration access
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "patch"]
  resourceNames: ["emergency-config", "incident-response"]

---
# Role Binding Template for Least Privilege
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: least-privilege-binding-template
  namespace: act-placemat
  labels:
    component: template
    data-residency: australia
    privilege-level: least
  annotations:
    description: "Template for least-privilege role bindings"
    compliance.framework: "australian-privacy-act"
    usage: "Replace ROLE_NAME and SERVICE_ACCOUNT with actual values"
subjects:
- kind: ServiceAccount
  name: REPLACE_WITH_SERVICE_ACCOUNT
  namespace: act-placemat
roleRef:
  kind: Role
  name: REPLACE_WITH_ROLE_NAME
  apiGroup: rbac.authorization.k8s.io