# Organization Policies for ACT Placemat Intelligence Hub
# Australian data residency and compliance enforcement through Kubernetes policies

---
# Australian Data Residency Organization Policy
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: australian-data-residency-policy
  labels:
    component: compliance
    data-residency: australia
    policy-type: organization
  annotations:
    description: "Enforces Australian data residency for all workloads"
    compliance.framework: "australian-privacy-act"
    policies.kyverno.io/title: "Australian Data Residency"
    policies.kyverno.io/category: "Compliance"
    policies.kyverno.io/severity: "high"
    policies.kyverno.io/subject: "Pod, PersistentVolumeClaim"
    policies.kyverno.io/description: "Ensures all workloads are scheduled only in Australian zones"
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: require-australian-node-affinity
    match:
      any:
      - resources:
          kinds:
          - Pod
          namespaces:
          - act-placemat
    validate:
      message: "Pods must have node affinity for Australian zones"
      pattern:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: "kubernetes.io/zone"
                    operator: In
                    values:
                    - "australia-southeast1-a"
                    - "australia-southeast1-b"
                    - "australia-southeast1-c"
                    - "australia-southeast2-a"
                    - "australia-southeast2-b"
                    - "australia-southeast2-c"
  - name: require-data-residency-label
    match:
      any:
      - resources:
          kinds:
          - Pod
          - Deployment
          - ReplicaSet
          - StatefulSet
          - DaemonSet
          namespaces:
          - act-placemat
    validate:
      message: "Resources must have data-residency=australia label"
      pattern:
        metadata:
          labels:
            data-residency: "australia"

---
# Australian Storage Compliance Policy
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: australian-storage-compliance-policy
  labels:
    component: compliance
    data-residency: australia
    policy-type: organization
  annotations:
    description: "Enforces Australian storage compliance for persistent volumes"
    compliance.framework: "australian-privacy-act"
    policies.kyverno.io/title: "Australian Storage Compliance"
    policies.kyverno.io/category: "Compliance"
    policies.kyverno.io/severity: "high"
    policies.kyverno.io/subject: "PersistentVolumeClaim, PersistentVolume"
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: require-australian-storage-class
    match:
      any:
      - resources:
          kinds:
          - PersistentVolumeClaim
          namespaces:
          - act-placemat
    validate:
      message: "PVCs must use Australian-compliant storage classes"
      pattern:
        spec:
          storageClassName: "australian-*"
  - name: require-australian-pv-zones
    match:
      any:
      - resources:
          kinds:
          - PersistentVolume
    validate:
      message: "PVs must be located in Australian zones"
      pattern:
        spec:
          nodeAffinity:
            required:
              nodeSelectorTerms:
              - matchExpressions:
                - key: "kubernetes.io/zone"
                  operator: In
                  values:
                  - "australia-southeast1-a"
                  - "australia-southeast1-b"
                  - "australia-southeast1-c"
                  - "australia-southeast2-a"
                  - "australia-southeast2-b"
                  - "australia-southeast2-c"

---
# Australian Security Context Policy
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: australian-security-context-policy
  labels:
    component: compliance
    data-residency: australia
    policy-type: organization
  annotations:
    description: "Enforces security context requirements for Australian compliance"
    compliance.framework: "australian-privacy-act"
    policies.kyverno.io/title: "Australian Security Context"
    policies.kyverno.io/category: "Security"
    policies.kyverno.io/severity: "high"
    policies.kyverno.io/subject: "Pod"
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: require-non-root-user
    match:
      any:
      - resources:
          kinds:
          - Pod
          namespaces:
          - act-placemat
    validate:
      message: "Containers must run as non-root user for Australian compliance"
      pattern:
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: ">0"
          containers:
          - securityContext:
              runAsNonRoot: true
              runAsUser: ">0"
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                - ALL
  - name: require-security-labels
    match:
      any:
      - resources:
          kinds:
          - Pod
          namespaces:
          - act-placemat
    validate:
      message: "Pods must have compliance and data classification labels"
      pattern:
        metadata:
          labels:
            compliance.framework: "australian-privacy-act"
            data.classification: "?*"

---
# Australian Network Policy Enforcement
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: australian-network-policy-enforcement
  labels:
    component: compliance
    data-residency: australia
    policy-type: organization
  annotations:
    description: "Enforces network policies for Australian data residency"
    compliance.framework: "australian-privacy-act"
    policies.kyverno.io/title: "Australian Network Policy"
    policies.kyverno.io/category: "Network"
    policies.kyverno.io/severity: "high"
    policies.kyverno.io/subject: "NetworkPolicy"
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: require-network-policy-for-namespace
    match:
      any:
      - resources:
          kinds:
          - Namespace
          names:
          - act-placemat
    generate:
      kind: NetworkPolicy
      apiVersion: networking.k8s.io/v1
      name: australian-compliance-network-policy
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      data:
        metadata:
          labels:
            data-residency: australia
            compliance-framework: australian-privacy-act
        spec:
          podSelector:
            matchLabels:
              data-residency: australia
          policyTypes:
          - Ingress
          - Egress
          ingress:
          - from:
            - namespaceSelector:
                matchLabels:
                  data-residency: australia
            - podSelector:
                matchLabels:
                  data-residency: australia
          egress:
          - to:
            - namespaceSelector:
                matchLabels:
                  data-residency: australia
            - podSelector:
                matchLabels:
                  data-residency: australia
          - to: []
            ports:
            - protocol: TCP
              port: 443
            - protocol: TCP
              port: 53
            - protocol: UDP
              port: 53

---
# Australian Encryption Policy
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: australian-encryption-policy
  labels:
    component: compliance
    data-residency: australia
    policy-type: organization
  annotations:
    description: "Enforces encryption requirements for Australian compliance"
    compliance.framework: "australian-privacy-act"
    policies.kyverno.io/title: "Australian Encryption Requirements"
    policies.kyverno.io/category: "Encryption"
    policies.kyverno.io/severity: "critical"
    policies.kyverno.io/subject: "Secret, ConfigMap"
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: require-encryption-for-secrets
    match:
      any:
      - resources:
          kinds:
          - Secret
          namespaces:
          - act-placemat
    validate:
      message: "Secrets must have encryption metadata for Australian compliance"
      pattern:
        metadata:
          annotations:
            encryption.type: "?*"
            data.classification: "?*"
            compliance.framework: "australian-privacy-act"
  - name: require-cmek-for-sensitive-data
    match:
      any:
      - resources:
          kinds:
          - Secret
          namespaces:
          - act-placemat
    validate:
      message: "Sensitive secrets must use CMEK encryption"
      anyPattern:
      - metadata:
          annotations:
            encryption.type: "cmek"
            cmek.key.id: "?*"
      - metadata:
          labels:
            data.classification: "public"
      - metadata:
          labels:
            data.classification: "community"

---
# Australian Audit Logging Policy
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: australian-audit-logging-policy
  labels:
    component: compliance
    data-residency: australia
    policy-type: organization
  annotations:
    description: "Enforces audit logging requirements for Australian compliance"
    compliance.framework: "australian-privacy-act"
    policies.kyverno.io/title: "Australian Audit Logging"
    policies.kyverno.io/category: "Audit"
    policies.kyverno.io/severity: "high"
    policies.kyverno.io/subject: "Pod, Service"
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: require-audit-annotations
    match:
      any:
      - resources:
          kinds:
          - Pod
          - Service
          - ConfigMap
          - Secret
          namespaces:
          - act-placemat
    validate:
      message: "Resources must have audit annotations for Australian compliance"
      pattern:
        metadata:
          annotations:
            audit.required: "?*"
            compliance.framework: "australian-privacy-act"
            data.classification: "?*"

---
# Australian Data Retention Policy
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: australian-data-retention-policy
  labels:
    component: compliance
    data-residency: australia
    policy-type: organization
  annotations:
    description: "Enforces data retention requirements for Australian compliance"
    compliance.framework: "australian-privacy-act"
    policies.kyverno.io/title: "Australian Data Retention"
    policies.kyverno.io/category: "Data Management"
    policies.kyverno.io/severity: "medium"
    policies.kyverno.io/subject: "ConfigMap, Secret"
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: require-retention-metadata
    match:
      any:
      - resources:
          kinds:
          - ConfigMap
          - Secret
          namespaces:
          - act-placemat
    exclude:
      any:
      - resources:
          names:
          - "kube-*"
          - "default-*"
    validate:
      message: "Data resources must have retention metadata for Australian compliance"
      pattern:
        metadata:
          annotations:
            retention.period: "?*"
            retention.policy: "?*"
            compliance.framework: "australian-privacy-act"

---
# Australian Access Control Policy
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: australian-access-control-policy
  labels:
    component: compliance
    data-residency: australia
    policy-type: organization
  annotations:
    description: "Enforces access control requirements for Australian compliance"
    compliance.framework: "australian-privacy-act"
    policies.kyverno.io/title: "Australian Access Control"
    policies.kyverno.io/category: "RBAC"
    policies.kyverno.io/severity: "high"
    policies.kyverno.io/subject: "Role, RoleBinding, ClusterRole, ClusterRoleBinding"
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: require-rbac-compliance-labels
    match:
      any:
      - resources:
          kinds:
          - Role
          - RoleBinding
          - ClusterRole
          - ClusterRoleBinding
    validate:
      message: "RBAC resources must have compliance labels"
      pattern:
        metadata:
          labels:
            data-residency: "australia"
          annotations:
            compliance.framework: "australian-privacy-act"
            last.reviewed: "?*"
            next.review: "?*"
  - name: prevent-wildcard-permissions
    match:
      any:
      - resources:
          kinds:
          - Role
          - ClusterRole
    validate:
      message: "Wildcard permissions are not allowed for Australian compliance"
      deny:
        conditions:
        - key: "{{ request.object.rules[?contains(verbs, '*')] | length(@) }}"
          operator: GreaterThan
          value: 0

---
# Australian Container Image Policy
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: australian-container-image-policy
  labels:
    component: compliance
    data-residency: australia
    policy-type: organization
  annotations:
    description: "Enforces container image compliance for Australian data residency"
    compliance.framework: "australian-privacy-act"
    policies.kyverno.io/title: "Australian Container Image Compliance"
    policies.kyverno.io/category: "Security"
    policies.kyverno.io/severity: "high"
    policies.kyverno.io/subject: "Pod"
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: require-australian-registry
    match:
      any:
      - resources:
          kinds:
          - Pod
          namespaces:
          - act-placemat
    validate:
      message: "Container images must be pulled from Australian registries"
      pattern:
        spec:
          containers:
          - image: "registry.actplacemat.org.au:5000/*"
  - name: require-signed-images
    match:
      any:
      - resources:
          kinds:
          - Pod
          namespaces:
          - act-placemat
    validate:
      message: "Container images must be signed for Australian compliance"
      pattern:
        metadata:
          annotations:
            cosign.signature.verified: "true"
            image.vulnerability.scan: "passed"

---
# Policy Exception for System Components
apiVersion: kyverno.io/v1
kind: PolicyException
metadata:
  name: australian-system-component-exception
  namespace: act-placemat
  labels:
    component: compliance
    data-residency: australia
  annotations:
    description: "Policy exceptions for system components"
    compliance.framework: "australian-privacy-act"
spec:
  exceptions:
  - policyName: australian-container-image-policy
    ruleNames:
    - require-australian-registry
  - policyName: australian-security-context-policy
    ruleNames:
    - require-non-root-user
  match:
  - any:
    - resources:
        kinds:
        - Pod
        names:
        - "kube-*"
        - "coredns-*"
        - "metrics-server-*"
        namespaces:
        - kube-system
        - kube-public

---
# Organization Policy Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: organization-policy-config
  namespace: act-placemat
  labels:
    component: compliance
    data-residency: australia
  annotations:
    description: "Configuration for organization policies"
    compliance.framework: "australian-privacy-act"
data:
  policy_enforcement_level: "strict"
  violation_action: "block"
  audit_logging: "enabled"
  compliance_monitoring: "enabled"
  
  # Australian data residency zones
  allowed_zones: |
    - australia-southeast1-a
    - australia-southeast1-b
    - australia-southeast1-c
    - australia-southeast2-a
    - australia-southeast2-b
    - australia-southeast2-c
  
  # Allowed storage classes
  allowed_storage_classes: |
    - australian-ssd
    - australian-standard
    - australian-backup
  
  # Required labels
  required_labels: |
    - data-residency: australia
    - compliance.framework: australian-privacy-act
    - data.classification: [public, community, internal, confidential, restricted]
  
  # Encryption requirements
  encryption_requirements: |
    public: optional
    community: recommended
    internal: required
    confidential: required
    restricted: required
  
  # Audit requirements
  audit_requirements: |
    public: basic
    community: standard
    internal: detailed
    confidential: comprehensive
    restricted: comprehensive
  
  # Retention periods
  retention_periods: |
    public: indefinite
    community: 7-years
    internal: 7-years
    confidential: 7-years
    restricted: 7-years