# IAM Permissions Audit for ACT Placemat Intelligence Hub
# Australian-compliant permission mapping and audit framework

---
# Permissions Audit ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: permissions-audit
  namespace: act-placemat
  labels:
    component: iam-audit
    data-residency: australia
  annotations:
    description: "Comprehensive permissions audit for multi-agent system"
    compliance.framework: "australian-privacy-act"
    audit.scope: "full-system"
data:
  # Agent Permission Requirements
  agent_permissions_matrix: |
    # Financial Intelligence Agent
    financial_intelligence:
      required_permissions:
        - "asic.company.read"
        - "abn.lookup.read"
        - "xero.accounting.read"
        - "data.financial.read"
        - "api.external.post"
        - "queue.tasks.read"
        - "queue.results.write"
        - "logs.agent.write"
        - "metrics.performance.write"
      data_access_level: "confidential"
      retention_period: "7-years"
      australian_processing_required: true
      
    # Research Analyst Agent
    research_analyst:
      required_permissions:
        - "web.scraping.read"
        - "data.public.read"
        - "api.research.post"
        - "notion.research.read"
        - "notion.research.write"
        - "queue.tasks.read"
        - "queue.results.write"
        - "logs.agent.write"
        - "metrics.performance.write"
      data_access_level: "internal"
      retention_period: "7-years"
      australian_processing_required: true
      
    # Compliance Officer Agent
    compliance_officer:
      required_permissions:
        - "audit.logs.read"
        - "compliance.rules.read"
        - "data.classification.read"
        - "data.classification.write"
        - "privacy.assessment.read"
        - "privacy.assessment.write"
        - "queue.tasks.read"
        - "queue.results.write"
        - "logs.compliance.write"
        - "alerts.compliance.write"
      data_access_level: "confidential"
      retention_period: "7-years"
      australian_processing_required: true
      
    # Community Coordinator Agent
    community_coordinator:
      required_permissions:
        - "community.engagement.read"
        - "community.engagement.write"
        - "democratic.voting.read"
        - "democratic.voting.write"
        - "consensus.building.read"
        - "consensus.building.write"
        - "notifications.community.write"
        - "queue.tasks.read"
        - "queue.results.write"
        - "logs.agent.write"
      data_access_level: "community"
      retention_period: "7-years"
      australian_processing_required: true

  # System Component Permissions
  system_permissions_matrix: |
    # Intelligence Hub Orchestrator
    intelligence_hub_orchestrator:
      required_permissions:
        - "agents.lifecycle.manage"
        - "workflows.orchestration.manage"
        - "tasks.routing.manage"
        - "state.management.read"
        - "state.management.write"
        - "queue.management.full"
        - "monitoring.system.read"
        - "logs.system.write"
        - "metrics.system.write"
      data_access_level: "internal"
      
    # Registry Services
    registry_services:
      required_permissions:
        - "images.registry.read"
        - "images.registry.write"
        - "vulnerabilities.scan.read"
        - "artifacts.metadata.read"
        - "artifacts.metadata.write"
        - "harbor.administration.manage"
      data_access_level: "operational"
      
    # Monitoring Services
    monitoring_services:
      required_permissions:
        - "metrics.collection.read"
        - "logs.aggregation.read"
        - "alerts.management.write"
        - "dashboards.management.write"
        - "health.checks.read"
        - "performance.metrics.read"
      data_access_level: "operational"

  # Australian Compliance Requirements
  australian_compliance_matrix: |
    # Data Residency Requirements
    data_residency:
      storage_location: "australia-southeast1,australia-southeast2"
      processing_location: "australia-only"
      backup_location: "australia-only"
      log_retention: "australia-only"
      
    # Privacy Act Compliance
    privacy_act_1988:
      personal_information_handling: "compliant"
      collection_notification: "required"
      use_limitation: "enforced"
      data_quality: "maintained"
      security_safeguards: "implemented"
      access_rights: "provided"
      correction_rights: "provided"
      
    # Audit Requirements
    audit_requirements:
      access_logging: "comprehensive"
      change_tracking: "enabled"
      compliance_reporting: "automated"
      incident_response: "documented"
      retention_enforcement: "7-years"

  # Risk Assessment Matrix
  risk_assessment_matrix: |
    # High Risk Permissions
    high_risk:
      - "data.financial.write"
      - "compliance.rules.write"
      - "system.administration.full"
      - "encryption.keys.manage"
      - "audit.logs.delete"
      - "privacy.data.delete"
      
    # Medium Risk Permissions
    medium_risk:
      - "data.financial.read"
      - "data.personal.read"
      - "api.external.post"
      - "notifications.external.send"
      - "reports.generate.confidential"
      
    # Low Risk Permissions
    low_risk:
      - "data.public.read"
      - "metrics.read"
      - "logs.read"
      - "health.check.read"
      - "status.read"

  # Permission Validation Rules
  validation_rules: |
    # Least Privilege Validation
    least_privilege:
      max_permissions_per_agent: 20
      require_justification: true
      regular_review_required: true
      removal_if_unused: "90-days"
      
    # Separation of Duties
    separation_of_duties:
      no_admin_and_audit: true
      no_read_and_delete: true
      no_create_and_approve: true
      
    # Australian Compliance Validation
    australian_compliance:
      data_residency_verified: true
      privacy_impact_assessed: true
      retention_policy_applied: true
      access_rights_implemented: true

---
# Permissions Audit CronJob
apiVersion: batch/v1
kind: CronJob
metadata:
  name: permissions-audit-job
  namespace: act-placemat
  labels:
    component: iam-audit
    data-residency: australia
  annotations:
    description: "Automated permissions audit for Australian compliance"
    compliance.framework: "australian-privacy-act"
spec:
  schedule: "0 1 * * 0"  # Weekly on Sunday at 1 AM AEDT
  timeZone: "Australia/Sydney"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            component: permissions-audit
            data-residency: australia
        spec:
          serviceAccountName: compliance-auditor
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            fsGroup: 1001
          containers:
          - name: permissions-auditor
            image: registry.actplacemat.org.au:5000/act-placemat/permissions-auditor:latest
            imagePullPolicy: Always
            env:
            - name: TZ
              value: "Australia/Sydney"
            - name: AUDIT_TYPE
              value: "permissions"
            - name: COMPLIANCE_FRAMEWORK
              value: "australian-privacy-act"
            - name: DATA_RESIDENCY
              value: "australia"
            command:
            - /bin/sh
            - -c
            - |
              echo "Starting permissions audit at $(date)"
              
              # Initialize audit report
              cat > /tmp/audit-report.json << EOF
              {
                "audit_date": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
                "audit_type": "permissions",
                "compliance_framework": "Australian Privacy Act 1988",
                "data_residency": "Australia",
                "findings": {
                  "total_roles": 0,
                  "total_service_accounts": 0,
                  "high_risk_permissions": [],
                  "unused_permissions": [],
                  "compliance_violations": [],
                  "recommendations": []
                },
                "compliance_status": "unknown"
              }
              EOF
              
              # Audit service accounts
              echo "Auditing service accounts..."
              SERVICE_ACCOUNTS=$(kubectl get sa -n act-placemat -o name | wc -l)
              echo "Found $SERVICE_ACCOUNTS service accounts"
              
              # Audit roles
              echo "Auditing roles..."
              ROLES=$(kubectl get roles -n act-placemat -o name | wc -l)
              echo "Found $ROLES roles"
              
              # Check for high-risk permissions
              echo "Checking for high-risk permissions..."
              HIGH_RISK_COUNT=0
              
              # Scan role bindings for high-risk patterns
              kubectl get rolebindings -n act-placemat -o json | jq -r '.items[] | .metadata.name' | while read binding; do
                ROLE_NAME=$(kubectl get rolebinding $binding -n act-placemat -o jsonpath='{.roleRef.name}')
                VERBS=$(kubectl get role $ROLE_NAME -n act-placemat -o jsonpath='{.rules[*].verbs[*]}' 2>/dev/null || echo "")
                
                if echo "$VERBS" | grep -q "delete\|*"; then
                  HIGH_RISK_COUNT=$((HIGH_RISK_COUNT + 1))
                  echo "High-risk permission found in binding: $binding (role: $ROLE_NAME)"
                fi
              done
              
              # Check Australian compliance
              echo "Checking Australian compliance..."
              NON_COMPLIANT=0
              
              # Check data residency labels
              kubectl get pods -n act-placemat -o json | jq -r '.items[] | select(.metadata.labels."data-residency" != "australia") | .metadata.name' > /tmp/non-compliant-pods.txt
              NON_COMPLIANT_PODS=$(cat /tmp/non-compliant-pods.txt | wc -l)
              
              if [ $NON_COMPLIANT_PODS -gt 0 ]; then
                NON_COMPLIANT=$((NON_COMPLIANT + NON_COMPLIANT_PODS))
                echo "Found $NON_COMPLIANT_PODS pods without Australian data residency labels"
              fi
              
              # Generate recommendations
              RECOMMENDATIONS=""
              if [ $HIGH_RISK_COUNT -gt 0 ]; then
                RECOMMENDATIONS="$RECOMMENDATIONS Review high-risk permissions for least-privilege compliance."
              fi
              if [ $NON_COMPLIANT_PODS -gt 0 ]; then
                RECOMMENDATIONS="$RECOMMENDATIONS Ensure all pods have data-residency=australia labels."
              fi
              
              # Determine compliance status
              COMPLIANCE_STATUS="COMPLIANT"
              if [ $HIGH_RISK_COUNT -gt 5 ] || [ $NON_COMPLIANT -gt 0 ]; then
                COMPLIANCE_STATUS="NON_COMPLIANT"
              elif [ $HIGH_RISK_COUNT -gt 0 ]; then
                COMPLIANCE_STATUS="REVIEW_REQUIRED"
              fi
              
              # Update audit report
              jq --arg total_roles "$ROLES" \
                 --arg total_sa "$SERVICE_ACCOUNTS" \
                 --arg high_risk "$HIGH_RISK_COUNT" \
                 --arg non_compliant "$NON_COMPLIANT" \
                 --arg status "$COMPLIANCE_STATUS" \
                 --arg recommendations "$RECOMMENDATIONS" \
                 '.findings.total_roles = ($total_roles | tonumber) |
                  .findings.total_service_accounts = ($total_sa | tonumber) |
                  .findings.high_risk_permissions_count = ($high_risk | tonumber) |
                  .findings.compliance_violations_count = ($non_compliant | tonumber) |
                  .findings.recommendations = [$recommendations] |
                  .compliance_status = $status' /tmp/audit-report.json > /tmp/audit-report-final.json
              
              # Store audit results
              kubectl create configmap permissions-audit-$(date +%Y%m%d) \
                --from-file=audit-report.json=/tmp/audit-report-final.json \
                --from-file=non-compliant-pods.txt=/tmp/non-compliant-pods.txt \
                -n act-placemat --dry-run=client -o yaml | kubectl apply -f -
              
              echo "Permissions audit completed at $(date)"
              echo "Compliance Status: $COMPLIANCE_STATUS"
              echo "High-risk permissions: $HIGH_RISK_COUNT"
              echo "Non-compliant resources: $NON_COMPLIANT"
            resources:
              limits:
                cpu: 200m
                memory: 512Mi
              requests:
                cpu: 100m
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 1001
              capabilities:
                drop:
                - ALL
            volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: audit-config
              mountPath: /app/config
              readOnly: true
          volumes:
          - name: tmp
            emptyDir: {}
          - name: audit-config
            configMap:
              name: permissions-audit
          imagePullSecrets:
          - name: registry-credentials
          nodeSelector:
            data-residency: australia

---
# Permissions Monitoring ServiceMonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: permissions-audit-metrics
  namespace: act-placemat
  labels:
    component: iam-audit
    data-residency: australia
  annotations:
    description: "Monitoring for permissions audit metrics"
    compliance.framework: "australian-privacy-act"
spec:
  selector:
    matchLabels:
      component: permissions-audit
  endpoints:
  - port: metrics
    interval: 300s
    path: /metrics
    honorLabels: true
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_label_data_residency]
      targetLabel: data_residency
    - sourceLabels: [__meta_kubernetes_pod_annotation_compliance_framework]
      targetLabel: compliance_framework

---
# Permissions Audit Alert Rules
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: permissions-audit-alerts
  namespace: act-placemat
  labels:
    component: iam-audit
    data-residency: australia
  annotations:
    description: "Alert rules for permissions audit"
    compliance.framework: "australian-privacy-act"
spec:
  groups:
  - name: permissions-audit
    rules:
    - alert: HighRiskPermissionsDetected
      expr: permissions_audit_high_risk_count > 5
      for: 0m
      labels:
        severity: warning
        component: iam-audit
        data_residency: australia
      annotations:
        summary: "High-risk permissions detected in IAM audit"
        description: "{{ $value }} high-risk permissions found during audit"
        
    - alert: ComplianceViolationDetected
      expr: permissions_audit_compliance_violations > 0
      for: 0m
      labels:
        severity: critical
        component: iam-audit
        data_residency: australia
      annotations:
        summary: "Australian compliance violation detected"
        description: "{{ $value }} compliance violations found during permissions audit"
        
    - alert: PermissionsAuditFailed
      expr: increase(permissions_audit_failures_total[1h]) > 0
      for: 0m
      labels:
        severity: critical
        component: iam-audit
        data_residency: australia
      annotations:
        summary: "Permissions audit job failed"
        description: "Permissions audit job has failed in the last hour"
        
    - alert: UnusedPermissionsDetected
      expr: permissions_audit_unused_permissions > 10
      for: 6h
      labels:
        severity: info
        component: iam-audit
        data_residency: australia
      annotations:
        summary: "Unused permissions detected"
        description: "{{ $value }} unused permissions found, consider removing for least-privilege compliance"